import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";

import type { BillingHandoff } from "../../types/billing";

const handoff: BillingHandoff = { id: 12, patient: { id: 2, first_name: "Maya", last_name: "Patient", full_name: "Maya Patient", gender: "Female", date_of_birth: null, age: 30, phone_number: "1", email: "", national_id_or_passport: null, blood_group: "", is_archived: false, version: 1, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" }, visit: { id: 6, status: "COMPLETED", started_at: "2026-01-01T09:00:00Z", completed_at: "2026-01-01T09:30:00Z", appointment: { id: 3, start_datetime: "2026-01-01T09:00:00Z", end_datetime: "2026-01-01T09:30:00Z", duration_minutes: 30, status: "COMPLETED", reason: "Review" } }, doctor: { id: 3, email: "doctor@example.test", full_name: "Doctor", role: "DOCTOR", is_active: true, theme_preference: "LIGHT", language_preference: "EN" }, note: "Ready", suggested_amount: "25.00", currency: "SYP", status: "PENDING", converted_invoice: null, dismissed_reason: "", created_by: null, updated_by: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" };
const state = vi.hoisted(() => ({ handoff: { data: null as BillingHandoff | null, isLoading: false, isError: false, refetch: vi.fn() }, mutations: { convert: { isPending: false, error: null, mutateAsync: vi.fn().mockResolvedValue({ id: 42 }) }, dismiss: { isPending: false, error: null, mutateAsync: vi.fn().mockResolvedValue({}) } } }));
vi.mock("../../features/billing/hooks/useBilling", () => ({ useHandoff: () => state.handoff, useBillingMutations: () => state.mutations }));

import { BillingHandoffDetailPage } from "./BillingPages";

function view(role: "ADMIN" | "STAFF" | "DOCTOR") { return render(<QueryClientProvider client={new QueryClient()}><MemoryRouter initialEntries={["/staff/billing/handoffs/12"]}><Routes><Route path="/staff/billing/handoffs/:handoffId" element={<BillingHandoffDetailPage role={role} />} /><Route path="/staff/billing/invoices/:invoiceId" element={<p>Invoice</p>} /></Routes></MemoryRouter></QueryClientProvider>); }

describe("Billing handoff production role and status matrix", () => {
  it("shows Staff Convert and Dismiss only for a pending handoff", () => { state.handoff.data = handoff; view("STAFF"); expect(screen.getByRole("button", { name: "Convert to invoice" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Dismiss handoff" })).toBeInTheDocument(); });
  it("keeps Admin, Doctor, converted, and dismissed handoffs read-only", () => { state.handoff.data = handoff; view("ADMIN"); expect(screen.queryByRole("button", { name: "Convert to invoice" })).not.toBeInTheDocument(); view("DOCTOR"); expect(screen.queryByRole("button", { name: "Dismiss handoff" })).not.toBeInTheDocument(); state.handoff.data = { ...handoff, status: "CONVERTED_TO_INVOICE" }; view("STAFF"); expect(screen.queryByRole("button", { name: "Convert to invoice" })).not.toBeInTheDocument(); state.handoff.data = { ...handoff, status: "DISMISSED", dismissed_reason: "Duplicate" }; view("STAFF"); expect(screen.queryByRole("button", { name: "Dismiss handoff" })).not.toBeInTheDocument(); });
  it("sends the exact conversion payload", () => { state.handoff.data = handoff; state.mutations.convert.mutateAsync.mockClear(); view("STAFF"); fireEvent.click(screen.getByRole("button", { name: "Convert to invoice" })); const convertButtons = screen.getAllByRole("button", { name: "Convert to invoice" }); fireEvent.submit(convertButtons[convertButtons.length - 1].closest("form")!); expect(state.mutations.convert.mutateAsync).toHaveBeenCalledWith({ handoffId: 12, payload: { total_amount: "25.00", currency: "SYP" } }); });
  it("sends the exact POST-only dismissal payload", () => { state.handoff.data = handoff; state.mutations.dismiss.mutateAsync.mockClear(); view("STAFF"); fireEvent.click(screen.getByRole("button", { name: "Dismiss handoff" })); const dismissButtons = screen.getAllByRole("button", { name: "Dismiss handoff" }); fireEvent.click(dismissButtons[dismissButtons.length - 1]); expect(state.mutations.dismiss.mutateAsync).toHaveBeenCalledWith({ handoffId: 12, reason: undefined }); });
  it("navigates once after a successful conversion", async () => { state.handoff.data = handoff; state.mutations.convert.mutateAsync.mockClear(); view("STAFF"); fireEvent.click(screen.getByRole("button", { name: "Convert to invoice" })); const convertButtons = screen.getAllByRole("button", { name: "Convert to invoice" }); fireEvent.submit(convertButtons[convertButtons.length - 1].closest("form")!); await waitFor(() => expect(screen.getAllByText("Invoice")).toHaveLength(1)); expect(state.mutations.convert.mutateAsync).toHaveBeenCalledTimes(1); });
});
