import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";

import type { BillingHandoff, Invoice, InvoicePrintData } from "../../types/billing";
const hookState = vi.hoisted(() => ({ handoffs: { data: { count: 0, results: [], previous: null, next: null }, isLoading: false, isError: false, refetch: vi.fn() }, invoices: { data: { count: 0, results: [], previous: null, next: null }, isLoading: false, isError: false, refetch: vi.fn() }, print: { data: null as InvoicePrintData | null, isLoading: false, isError: false, refetch: vi.fn() }, createInvoice: { isPending: false, error: null, mutateAsync: vi.fn().mockResolvedValue({ id: 9 }) } }));
vi.mock("../../features/billing/hooks/useBilling", () => ({ useHandoffs: () => hookState.handoffs, useInvoices: () => hookState.invoices, useInvoicePrintData: () => hookState.print, useHandoff: () => hookState.handoffs, useInvoice: () => hookState.invoices, useInvoicePayments: () => ({ data: [] }), useBillingMutations: () => ({ createInvoice: hookState.createInvoice }) }));
vi.mock("../../api/endpoints/patients", () => ({ getPatients: vi.fn().mockResolvedValue({ results: [{ id: 7, first_name: "Maya", last_name: "Patient", full_name: "Maya Patient", gender: "Female", date_of_birth: null, age: 30, phone_number: "1", email: "", national_id_or_passport: null, blood_group: "", is_archived: false, version: 1, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" }] }) }));
vi.mock("../../api/endpoints/appointments", () => ({ getAppointments: vi.fn().mockResolvedValue({ results: [] }) }));
vi.mock("../../features/patients/hooks/usePatient", () => ({ usePatientVisits: () => ({ data: { results: [] } }) }));
import { BillingHandoffListPage, InvoiceListPage, InvoicePrintPage, NewInvoicePage } from "./BillingPages";

function wrap(node: React.ReactNode, path = "/staff/billing/invoices") { return render(<QueryClientProvider client={new QueryClient()}><MemoryRouter initialEntries={[path]}>{node}</MemoryRouter></QueryClientProvider>); }
describe("Billing production pages", () => {
  it("keeps Admin invoices read-only and Staff receives the new-invoice action", () => { wrap(<InvoiceListPage role="ADMIN" />); expect(screen.queryByRole("link", { name: "New invoice" })).not.toBeInTheDocument(); wrap(<InvoiceListPage role="STAFF" />); expect(screen.getByRole("link", { name: "New invoice" })).toBeInTheDocument(); });
  it("renders meaningful handoff list states and preserves URL filters", () => { wrap(<BillingHandoffListPage role="DOCTOR" />, "/doctor/billing/handoffs?status=PENDING"); expect(screen.getByLabelText("Status")).toHaveValue("PENDING"); expect(screen.getByText("No billing handoffs found.")).toBeInTheDocument(); });
  it("renders structured print data without a JSON or preformatted dump", () => { hookState.print.data = { clinic: { clinic_name: "Pearlix", address: "Damascus", phone_number: "1", email: "a@b.test" }, invoice: { invoice_number: "INV-1", status: "UNPAID", created_at: "2026-01-01T00:00:00Z", cancelled_at: null, cancelled_reason: "" }, patient: { id: 1, full_name: "Maya", phone_number: "2" }, visit: null, appointment: null, currency: "SYP", total_amount: "10.00", paid_amount: "0.00", remaining_amount: "10.00", notes: "", payments: [] } satisfies InvoicePrintData; wrap(<InvoicePrintPage role="ADMIN" />, "/admin/billing/invoices/1/print"); expect(screen.getByText("Pearlix")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Print" })).toBeInTheDocument(); expect(document.querySelector("pre")).toBeNull(); });
  it("creates an invoice from a selected patient instead of a raw patient identifier", async () => { hookState.createInvoice.mutateAsync.mockClear(); wrap(<NewInvoicePage />, "/staff/billing/invoices/new"); fireEvent.change(screen.getByRole("textbox", { name: "Search patient" }), { target: { value: "Maya" } }); await waitFor(() => expect(screen.getByRole("button", { name: "Maya Patient" })).toBeInTheDocument()); fireEvent.click(screen.getByRole("button", { name: "Maya Patient" })); fireEvent.change(screen.getByRole("textbox", { name: "Total amount" }), { target: { value: "25.00" } }); fireEvent.submit(screen.getByRole("button", { name: "Create" }).closest("form")!); await waitFor(() => expect(hookState.createInvoice.mutateAsync).toHaveBeenCalledWith({ patient_id: 7, total_amount: "25.00", currency: "USD" })); });
});
