import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, RouterProvider, createMemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";

import type { BillingHandoff, Invoice, InvoicePrintData } from "../../types/billing";
import { useAuthStore } from "../../auth/authStore";
import type { AuthUser } from "../../types/auth";
class JsdomRequest { readonly body: null = null; readonly headers: Headers; readonly method: string; readonly signal: AbortSignal; readonly url: string; constructor(input: string | URL, init: RequestInit = {}) { this.url = String(input); this.method = init.method ?? "GET"; this.headers = new Headers(init.headers); this.signal = init.signal ?? new AbortController().signal; } }
Object.defineProperty(globalThis, "Request", { configurable: true, value: JsdomRequest });
const hookState = vi.hoisted(() => ({ handoffs: { data: { count: 0, results: [], previous: null, next: null }, isLoading: false, isError: false, refetch: vi.fn() }, invoices: { data: { count: 0, results: [], previous: null, next: null }, isLoading: false, isError: false, refetch: vi.fn() }, handoffQuery: {} as Record<string, string | number | undefined>, invoiceQuery: {} as Record<string, string | number | undefined>, print: { data: null as InvoicePrintData | null, isLoading: false, isError: false, refetch: vi.fn() }, createInvoice: { isPending: false, error: null, mutateAsync: vi.fn().mockResolvedValue({ id: 9 }) } }));
vi.mock("../../features/billing/hooks/useBilling", () => ({ useHandoffs: (query: Record<string, string | number | undefined>) => { hookState.handoffQuery = query; return hookState.handoffs; }, useInvoices: (query: Record<string, string | number | undefined>) => { hookState.invoiceQuery = query; return hookState.invoices; }, useInvoicePrintData: () => hookState.print, useHandoff: () => hookState.handoffs, useInvoice: () => hookState.invoices, useInvoicePayments: () => ({ data: [] }), useBillingMutations: () => ({ createInvoice: hookState.createInvoice }) }));
vi.mock("../../api/endpoints/patients", () => ({ getPatients: vi.fn().mockResolvedValue({ results: [{ id: 7, first_name: "Maya", last_name: "Patient", full_name: "Maya Patient", gender: "Female", date_of_birth: null, age: 30, phone_number: "1", email: "", national_id_or_passport: null, blood_group: "", is_archived: false, version: 1, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" }] }) }));
vi.mock("../../api/endpoints/appointments", () => ({ getAppointments: vi.fn().mockResolvedValue({ results: [] }) }));
vi.mock("../../features/patients/hooks/usePatient", () => ({ usePatientVisits: () => ({ data: { results: [] } }) }));
import { BillingHandoffListPage, InvoiceListPage, InvoicePrintPage, NewInvoicePage } from "./BillingPages";

function wrap(node: React.ReactNode, path = "/staff/billing/invoices") { return render(<QueryClientProvider client={new QueryClient()}><MemoryRouter initialEntries={[path]}>{node}</MemoryRouter></QueryClientProvider>); }
function renderNewInvoice() { const router = createMemoryRouter([{ path: "/staff/billing/invoices/new", element: <NewInvoicePage /> }, { path: "/staff/billing/invoices", element: <p>Invoices</p> }, { path: "/staff/billing/invoices/:invoiceId", element: <p>Invoice detail</p> }], { initialEntries: ["/staff/billing/invoices/new"] }); return { router, ...render(<QueryClientProvider client={new QueryClient()}><RouterProvider router={router} /></QueryClientProvider>) }; }
describe("Billing production pages", () => {
  afterEach(() => { document.documentElement.dir = "ltr"; useAuthStore.setState({ user: null, role: null }); });
  it("keeps Admin read-only and removes the normal Staff New Invoice action", () => { wrap(<InvoiceListPage role="ADMIN" />); expect(screen.queryByRole("link", { name: "New invoice" })).not.toBeInTheDocument(); wrap(<InvoiceListPage role="STAFF" />); expect(screen.queryByRole("link", { name: "New invoice" })).not.toBeInTheDocument(); });
  it("renders meaningful handoff list states and preserves URL filters", () => { wrap(<BillingHandoffListPage role="DOCTOR" />, "/doctor/billing/handoffs?status=PENDING"); expect(screen.getByLabelText("Status")).toHaveValue("PENDING"); expect(screen.queryByRole("combobox", { name: "Filter doctors" })).not.toBeInTheDocument(); expect(hookState.handoffQuery).toMatchObject({ page: 1, status: "PENDING" }); expect(screen.getByText("No billing handoffs found.")).toBeInTheDocument(); });
  it("renders structured A4 print data and screen controls without a JSON or preformatted dump", () => { hookState.print.data = { clinic: { clinic_name: "Pearlix", address: "Damascus", phone_number: "1", email: "a@b.test" }, invoice: { invoice_number: "INV-1", status: "UNPAID", created_at: "2026-01-01T00:00:00Z", cancelled_at: null, cancelled_reason: "" }, patient: { id: 1, full_name: "Maya", phone_number: "2" }, visit: null, appointment: null, currency: "SYP", total_amount: "10.00", paid_amount: "0.00", remaining_amount: "10.00", notes: "", payments: [] } satisfies InvoicePrintData; wrap(<InvoicePrintPage role="ADMIN" />, "/admin/billing/invoices/1/print"); expect(screen.getByText("Pearlix")).toBeInTheDocument(); expect(document.querySelector("article.a4-invoice")).toBeInTheDocument(); expect(document.querySelector(".print-control")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Back" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Print" })).toBeInTheDocument(); expect(document.querySelector("pre")).toBeNull(); });
  it("preserves Arabic root RTL direction for the production print view", () => { const user: AuthUser = { id: 1, email: "admin@example.test", full_name: "Admin", role: "ADMIN", is_active: true, theme_preference: "LIGHT", language_preference: "AR", must_change_password: false, password_changed_at: null }; useAuthStore.setState({ user }); document.documentElement.dir = "rtl"; hookState.print.data = { clinic: { clinic_name: "Pearlix", address: "Damascus", phone_number: "1", email: "a@b.test" }, invoice: { invoice_number: "INV-2", status: "UNPAID", created_at: "2026-01-01T00:00:00Z", cancelled_at: null, cancelled_reason: "" }, patient: { id: 1, full_name: "Maya", phone_number: "2" }, visit: null, appointment: null, currency: "SYP", total_amount: "10.00", paid_amount: "0.00", remaining_amount: "10.00", notes: "", payments: [] }; wrap(<InvoicePrintPage role="ADMIN" />, "/admin/billing/invoices/2/print"); const printView = document.querySelector("main.print-invoice"); expect(printView?.closest("[dir]")).toHaveAttribute("dir", "rtl"); expect(printView).not.toHaveAttribute("dir"); });
  it("exposes controlled list filters without raw identifier fields", async () => { const handoffView = wrap(<BillingHandoffListPage role="STAFF" />, "/staff/billing/handoffs?page=3"); const handoff = within(handoffView.container); expect(handoff.getByRole("combobox", { name: "Filter doctors" })).toBeInTheDocument(); expect(handoff.getByRole("combobox", { name: "Filter patients" })).toBeInTheDocument(); expect(handoff.queryByLabelText(/doctor id|patient id|visit id/i)).not.toBeInTheDocument(); fireEvent.change(handoff.getByLabelText("Created from"), { target: { value: "2026-01-01" } }); await waitFor(() => expect(hookState.handoffQuery).toMatchObject({ page: 1, created_from: "2026-01-01" })); expect(handoff.getByLabelText("Created from")).toHaveValue("2026-01-01"); handoffView.unmount(); const invoiceView = wrap(<InvoiceListPage role="ADMIN" />, "/admin/billing/invoices?currency=SYP"); const invoice = within(invoiceView.container); expect(invoice.getByRole("combobox", { name: "Currency" })).toHaveValue("SYP"); expect(invoice.getByRole("combobox", { name: "Filter patients" })).toBeInTheDocument(); expect(hookState.invoiceQuery).toMatchObject({ page: 1, currency: "SYP" }); });
  it("creates an invoice from a selected patient instead of a raw patient identifier", async () => { hookState.createInvoice.mutateAsync.mockClear(); renderNewInvoice(); fireEvent.change(screen.getByRole("textbox", { name: "Search patient" }), { target: { value: "Maya" } }); await waitFor(() => expect(screen.getByRole("button", { name: "Maya Patient" })).toBeInTheDocument()); fireEvent.click(screen.getByRole("button", { name: "Maya Patient" })); fireEvent.change(screen.getByRole("textbox", { name: "Total amount" }), { target: { value: "25.00" } }); fireEvent.submit(screen.getByRole("button", { name: "Create" }).closest("form")!); await waitFor(() => expect(hookState.createInvoice.mutateAsync).toHaveBeenCalledWith({ patient_id: 7, total_amount: "25.00", currency: "USD" })); await screen.findByText("Invoice detail"); });
  it("protects dirty New Invoice navigation and beforeunload while preserving a failed create", async () => { const { router } = renderNewInvoice(); const unload = new Event("beforeunload", { cancelable: true }); expect(window.dispatchEvent(unload)).toBe(true); fireEvent.change(screen.getByRole("textbox", { name: "Search patient" }), { target: { value: "Maya" } }); await waitFor(() => expect(screen.getByRole("button", { name: "Maya Patient" })).toBeInTheDocument()); fireEvent.click(screen.getByRole("button", { name: "Maya Patient" })); expect(window.dispatchEvent(new Event("beforeunload", { cancelable: true }))).toBe(false); await act(async () => { await router.navigate("/staff/billing/invoices"); }); expect(await screen.findByRole("dialog", { name: "Discard unsaved changes?" })).toBeInTheDocument(); expect(router.state.location.pathname).toBe("/staff/billing/invoices/new"); fireEvent.click(screen.getByRole("button", { name: "Keep editing" })); hookState.createInvoice.mutateAsync.mockRejectedValueOnce(new Error("Billing unavailable")); fireEvent.change(screen.getByRole("textbox", { name: "Total amount" }), { target: { value: "25.00" } }); fireEvent.submit(screen.getByRole("button", { name: "Create" }).closest("form")!); await waitFor(() => expect(hookState.createInvoice.mutateAsync).toHaveBeenCalled()); expect(screen.getByRole("textbox", { name: "Total amount" })).toHaveValue("25.00"); expect(screen.getByRole("button", { name: "Maya Patient" })).toBeInTheDocument(); });
});
