import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, CalendarSync, CircleDollarSign, ClipboardCheck, ReceiptText, Stethoscope, UsersRound } from "lucide-react";
import { KpiCard, PageHeaderV2, PreviewList, SectionHeading, Skeleton, StatePanel, SurfaceCard, StatusBadge } from "../../components/v2";
import { formatDateRange } from "../../utils/dates";
import type { DashboardAppointmentSummary, DashboardBillingHandoffSummary, DashboardVisitSummary } from "../../types/dashboard";

export const today = new Date().toISOString().slice(0, 10);
export function DashboardLoading() { return <><Skeleton height={48} /><div className="dashboard-grid">{Array.from({ length: 5 }, (_, i) => <Skeleton key={i} height={140} />)}</div></>; }
export function DashboardError({ retry }: { retry: () => void }) { return <StatePanel state="error" title="Unable to load dashboard" description="The clinic dashboard could not be retrieved." action={<button className="v2-button secondary" onClick={retry}>Retry</button>} />; }
export function Kpis({ items }: { items: Array<{ label: string; value: number; support: string; to: string; icon: ReactNode }> }) { return <div className="dashboard-grid">{items.map((item) => <Link key={item.label} to={item.to} className="kpi-link"><KpiCard {...item} /></Link>)}</div>; }
export function AppointmentPreview({ title, items, to, empty }: { title: string; items: DashboardAppointmentSummary[]; to: string; empty: string }) { return <SurfaceCard><SectionHeading title={title} /><PreviewList initialCount={4} items={items} viewAll={<Link className="v2-button secondary compact" to={to}>View all</Link>} renderItem={(item) => <Link className="summary-row" key={item.id} to={to}><span><strong>{item.patient.full_name}</strong><small>{formatDateRange(item.start_datetime, item.end_datetime)} · {item.doctor.full_name}</small></span><StatusBadge status={item.status} /></Link>} />{items.length === 0 ? <StatePanel state="empty" title={empty} /> : null}</SurfaceCard>; }
export function HandoffPreview({ title, items, to }: { title: string; items: DashboardBillingHandoffSummary[]; to: string }) { return <SurfaceCard><SectionHeading title={title} /><PreviewList initialCount={4} items={items} viewAll={<Link className="v2-button secondary compact" to={to}>View all</Link>} renderItem={(item) => <Link className="summary-row" key={item.id} to={to}><span><strong>{item.patient.full_name}</strong><small>Visit {item.visit_id}</small></span><StatusBadge status={item.status} /></Link>} />{items.length === 0 ? <StatePanel state="empty" title="No handoffs are waiting" /> : null}</SurfaceCard>; }
export function VisitPreview({ items, to }: { items: DashboardVisitSummary[]; to: string }) { return <SurfaceCard><SectionHeading title="Recent visits" /><PreviewList initialCount={4} items={items} viewAll={<Link className="v2-button secondary compact" to={to}>View all</Link>} renderItem={(item) => <Link className="summary-row" key={item.id} to={`/doctor/visits/${item.id}`}><span><strong>{item.patient.full_name}</strong><small>Visit {item.appointment_id}</small></span><StatusBadge status={item.status} /></Link>} />{items.length === 0 ? <StatePanel state="empty" title="No recent visits" /> : null}</SurfaceCard>; }
export const Icons = { patients: <UsersRound />, appointments: <CalendarDays />, reschedule: <CalendarSync />, handoff: <ReceiptText />, money: <CircleDollarSign />, active: <Stethoscope />, complete: <ClipboardCheck /> };
