import { AlertCircle, CheckCircle2, ChevronRight, Circle, Info, Lock, Search, X } from "lucide-react";
import type { ButtonHTMLAttributes, InputHTMLAttributes, PropsWithChildren, ReactNode, SelectHTMLAttributes } from "react";
import { createContext, useContext, useEffect, useId, useMemo, useRef, useState } from "react";
import { useFeatureT } from "../layouts/i18n";

export function Button({ children, variant = "primary", compact, loading = false, disabled, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger"; compact?: boolean; loading?: boolean }) { return <button {...props} disabled={disabled || loading} aria-busy={loading || undefined} className={["v2-button", variant === "primary" ? "" : variant, compact ? "compact" : "", props.className].filter(Boolean).join(" ")}>{children}</button>; }
export function IconButton({ label, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button {...props} className={["v2-icon-button", props.className].filter(Boolean).join(" ")} aria-label={label} data-tooltip={label}>{children}</button>; }
export function PageHeaderV2({ title, description, action }: { title:string; description?:string; action?:ReactNode }) { return <div className="page-header"><div><h2>{title}</h2>{description ? <p>{description}</p> : null}</div>{action ? <div className="page-header-actions">{action}</div> : null}</div>; }
export function SectionHeading({ title, description }: { title:string; description?:string }) { return <div className="section-header"><h3>{title}</h3>{description ? <p>{description}</p> : null}</div>; }
export function SurfaceCard({ children, major = false, className }: PropsWithChildren<{ major?:boolean; className?:string }>) { return <section className={["v2-card", major ? "major" : "", className].filter(Boolean).join(" ")}>{children}</section>; }
export type KpiTone = "info" | "success" | "warning" | "danger";
export function KpiCard({ icon, label, value, helper, action, tone = "info" }: { icon:ReactNode; label:string; value:string|number; helper?:string; action?:string; tone?:KpiTone }) { return <SurfaceCard className={`kpi-card ${tone}`}><div className="kpi-icon" aria-hidden="true">{icon}</div><p className="kpi-label">{label}</p><strong className="kpi-value">{value}</strong>{helper ? <span className="kpi-helper">{helper}</span> : null}{action ? <span className="kpi-footer">{action}<ChevronRight size={16} aria-hidden="true" /></span> : null}</SurfaceCard>; }

const statusMeta: Record<string, { tone:string; icon:typeof Circle; en:string; ar:string }> = { ACTIVE:{ tone:"success", icon:CheckCircle2, en:"Active", ar:"نشط" }, INACTIVE:{ tone:"danger", icon:X, en:"Inactive", ar:"غير نشط" }, UPCOMING:{ tone:"", icon:Circle, en:"Upcoming", ar:"قادم" }, CHECKED_IN:{ tone:"success", icon:CheckCircle2, en:"Checked in", ar:"تم تسجيل الحضور" }, COMPLETED:{ tone:"success", icon:CheckCircle2, en:"Completed", ar:"مكتمل" }, PAID:{ tone:"success", icon:CheckCircle2, en:"Paid", ar:"مدفوع" }, CONVERTED_TO_INVOICE:{ tone:"success", icon:CheckCircle2, en:"Converted to invoice", ar:"تم التحويل إلى فاتورة" }, CANCELLED:{ tone:"danger", icon:X, en:"Cancelled", ar:"ملغى" }, NO_SHOW:{ tone:"danger", icon:X, en:"No-show", ar:"لم يحضر" }, FAILED:{ tone:"danger", icon:AlertCircle, en:"Failed", ar:"فشل" }, DISMISSED:{ tone:"danger", icon:AlertCircle, en:"Dismissed", ar:"مرفوض" }, NEEDS_RESCHEDULE:{ tone:"warning", icon:AlertCircle, en:"Needs reschedule", ar:"يحتاج إعادة جدولة" }, UNPAID:{ tone:"warning", icon:AlertCircle, en:"Unpaid", ar:"غير مدفوع" }, PARTIALLY_PAID:{ tone:"warning", icon:AlertCircle, en:"Partially paid", ar:"مدفوع جزئياً" }, PENDING:{ tone:"warning", icon:AlertCircle, en:"Pending", ar:"قيد الانتظار" }, AI_COMPLETED:{ tone:"ai", icon:Info, en:"AI completed", ar:"اكتمل الذكاء الاصطناعي" } };
export function statusLabel(status: string) { const meta = statusMeta[status] ?? { tone:"", icon:Circle, en:"Not recorded", ar:"غير مسجل" }; return typeof document !== "undefined" && document.documentElement.lang === "ar" ? meta.ar : meta.en; }
export function StatusBadge({ status }: { status:string }) { const meta = statusMeta[status] ?? { tone:"", icon:Circle, en:"Not recorded", ar:"غير مسجل" }; const text = statusLabel(status); const Icon = meta.icon; return <span className={`v2-status ${meta.tone}`} aria-label={`Status: ${text}`}><Icon size={14} strokeWidth={1.75} aria-hidden="true" />{text}</span>; }

export function Tabs({ tabs, selected, onSelect }: { tabs:{ id:string; label:string }[]; selected:string; onSelect:(id:string)=>void }) { return <div className="v2-tabs" role="tablist">{tabs.map((tab, index) => <button key={tab.id} className="v2-tab" role="tab" aria-selected={selected === tab.id} tabIndex={selected === tab.id ? 0 : -1} onKeyDown={(event) => { if (event.key === "ArrowRight" || event.key === "ArrowLeft") { event.preventDefault(); onSelect(tabs[(index + (event.key === "ArrowRight" ? 1 : tabs.length - 1)) % tabs.length].id); } }} onClick={() => onSelect(tab.id)}>{tab.label}</button>)}</div>; }
export function DataTableShell({ title, count, toolbar, children, state }: PropsWithChildren<{ title:string; count?:number; toolbar?:ReactNode; state?:ReactNode }>) { return <SurfaceCard className="v2-table-shell"><div className="v2-table-toolbar"><h3>{title}{count !== undefined ? ` (${count})` : ""}</h3>{toolbar}</div><div className="v2-table-scroll">{state ?? children}</div></SurfaceCard>; }
export function ClickableRow({ children, onOpen }: PropsWithChildren<{ onOpen:()=>void }>) { const canOpen = (target:EventTarget) => !(target instanceof Element && target.closest("button,a,input,select,textarea,[data-row-action]")); return <tr className="v2-clickable-row" tabIndex={0} onClick={(event) => { if (canOpen(event.target)) onOpen(); }} onKeyDown={(event) => { if ((event.key === "Enter" || event.key === " ") && canOpen(event.target)) { event.preventDefault(); onOpen(); } }}>{children}<td aria-hidden="true"><ChevronRight size={16} /></td></tr>; }
export function PreviewList<T>({ items, renderItem, initialCount = 5, viewAll }: { items:T[]; renderItem:(item:T, index:number)=>ReactNode; initialCount?:number; viewAll?:ReactNode }) { const [expanded, setExpanded] = useState(false); const t = useFeatureT(); const visible = expanded ? items : items.slice(0, initialCount); return <div className="summary-list"><ul>{visible.map(renderItem)}</ul>{items.length > initialCount ? <Button compact variant="secondary" type="button" onClick={() => setExpanded(!expanded)}>{expanded ? t("collapse") : `${t("showMore")} (${items.length - initialCount})`}</Button> : null}{viewAll}</div>; }
export function Pagination({ page, hasPrevious, hasNext, onPrevious, onNext }: { page:number; hasPrevious:boolean; hasNext:boolean; onPrevious:()=>void; onNext:()=>void }) { return <div className="pagination-bar"><span>Page {page}</span><div><Button compact variant="secondary" disabled={!hasPrevious} onClick={onPrevious}>Previous</Button><Button compact variant="secondary" disabled={!hasNext} onClick={onNext}>Next</Button></div></div>; }
export function DetailHeader({ title, summary, action }: { title:string; summary?:string; action?:ReactNode }) { return <PageHeaderV2 title={title} description={summary} action={action} />; }

export function Field({ label, error, help, ...props }: InputHTMLAttributes<HTMLInputElement> & { label:string; error?:string; help?:string }) { const id = useId(); const descriptionId = error || help ? `${id}-description` : undefined; return <div className="v2-field"><label htmlFor={id}>{label}</label><input {...props} id={id} aria-invalid={Boolean(error)} aria-describedby={descriptionId} />{error ? <span id={descriptionId} className="v2-field-error" role="alert">{error}</span> : help ? <span id={descriptionId}>{help}</span> : null}</div>; }
export function SelectField({ label, error, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label:string; error?:string; children:ReactNode }) { const id = useId(); return <div className="v2-field"><label htmlFor={id}>{label}</label><select {...props} id={id} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined}>{children}</select>{error ? <span id={`${id}-error`} className="v2-field-error" role="alert">{error}</span> : null}</div>; }
export function Combobox({ label, value, onChange, options, placeholder = "Search", error, onQueryChange }: { label:string; value:string; onChange:(value:string)=>void; options:{ value:string; label:string }[]; placeholder?:string; error?:string; onQueryChange?:(query:string)=>void }) {
  const id = useId(); const [open, setOpen] = useState(false); const [active, setActive] = useState(0);
  const selected = options.find((option) => option.value === value);
  const [query, setQuery] = useState(selected?.label ?? "");
  useEffect(() => { setQuery(selected?.label ?? ""); }, [selected?.label, value]);
  const filtered = useMemo(() => options.filter((option) => option.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [options, query]);
  useEffect(() => setActive((index) => Math.max(0, Math.min(index, filtered.length - 1))), [filtered.length]);
  const choose = (option:{ value:string; label:string }) => { onChange(option.value); setQuery(option.label); setOpen(false); };
  const descriptionId = error ? `${id}-error` : undefined;
  return <div className="v2-field"><label htmlFor={id}>{label}</label><div className="combobox"><Search size={18} aria-hidden="true" /><input id={id} role="combobox" aria-autocomplete="list" aria-controls={`${id}-options`} aria-activedescendant={open && filtered[active] ? `${id}-option-${filtered[active].value}` : undefined} aria-describedby={descriptionId} aria-invalid={Boolean(error)} aria-expanded={open} value={query} placeholder={placeholder} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); onQueryChange?.(event.target.value); setOpen(true); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActive((index) => Math.min(index + 1, Math.max(0, filtered.length - 1))); } else if (event.key === "ArrowUp") { event.preventDefault(); setOpen(true); setActive((index) => Math.max(index - 1, 0)); } else if (event.key === "Enter" && open && filtered[active]) { event.preventDefault(); choose(filtered[active]); } else if (event.key === "Escape") { event.preventDefault(); setOpen(false); setQuery(selected?.label ?? ""); } }} />{open ? <ul id={`${id}-options`} role="listbox">{filtered.map((option) => <li id={`${id}-option-${option.value}`} key={option.value} role="option" aria-selected={option.value === value}><button type="button" className="bidi-isolate" onMouseDown={(event) => event.preventDefault()} onClick={() => choose(option)}>{option.label}</button></li>)}</ul> : null}</div>{error ? <span id={descriptionId} className="v2-field-error" role="alert">{error}</span> : null}</div>;
}
export function FormSection({ title, children }: PropsWithChildren<{ title:string }>) { return <section className="v2-form-section"><h3>{title}</h3><div className="v2-form-grid">{children}</div></section>; }
export function StickyActionBar({ children }: PropsWithChildren) { return <div className="v2-sticky-actions">{children}</div>; }

type OverlayProps = PropsWithChildren<{ open:boolean; title:string; description?:string; onClose:()=>void; dirty?:boolean; pending?:boolean; wide?:boolean }>;
const OverlayCloseContext = createContext<() => void>(() => undefined);
export function useOverlayClose() { return useContext(OverlayCloseContext); }
function Overlay({ open, title, description, onClose, dirty = false, pending = false, wide, children, drawer = false }: OverlayProps & { drawer?:boolean }) { const dialog = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLElement | null>(null); const [confirmDiscard, setConfirmDiscard] = useState(false); const t = useFeatureT(); function requestClose() { if (pending) return; if (dirty) { setConfirmDiscard(true); return; } onClose(); } useEffect(() => { if (!open) { setConfirmDiscard(false); return; } trigger.current = document.activeElement as HTMLElement; const timer = window.setTimeout(() => dialog.current?.querySelector<HTMLElement>("button, input, select, textarea, [tabindex]:not([tabindex='-1'])")?.focus(), 0); const onKey = (event:KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); requestClose(); } if (event.key === "Tab" && dialog.current) { const focusable = Array.from(dialog.current.querySelectorAll<HTMLElement>("button, input, select, textarea, [tabindex]:not([tabindex='-1'])")); const last = focusable[focusable.length - 1]; if (!focusable.length) return; if (event.shiftKey && document.activeElement === focusable[0]) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); focusable[0].focus(); } } }; document.addEventListener("keydown", onKey); return () => { clearTimeout(timer); document.removeEventListener("keydown", onKey); window.setTimeout(() => trigger.current?.focus(), 0); }; }, [open, dirty, pending]); if (!open) return null; return <div className="v2-overlay-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) requestClose(); }}><div className={`v2-overlay ${drawer ? "drawer" : ""} ${wide ? "wide" : ""}`} role="dialog" aria-modal="true" aria-labelledby="overlay-title" aria-describedby={description ? "overlay-description" : undefined} ref={dialog}><div className="v2-overlay-header"><div><h2 id="overlay-title">{title}</h2>{description ? <p id="overlay-description">{description}</p> : null}</div><IconButton label={t("close")} onClick={requestClose} disabled={pending}><X size={20} /></IconButton></div><OverlayCloseContext.Provider value={requestClose}>{children}</OverlayCloseContext.Provider>{confirmDiscard ? <div className="v2-discard-dialog" role="alertdialog" aria-modal="true" aria-label={t("discardChanges")}><p>{t("discardChanges")}</p><Button variant="danger" onClick={onClose}>{t("discard")}</Button><Button variant="secondary" onClick={() => setConfirmDiscard(false)}>{t("keepEditing")}</Button></div> : null}</div></div>; }
export function Modal(props:OverlayProps) { return <Overlay {...props} />; } export function Drawer(props:OverlayProps) { return <Overlay {...props} drawer />; } export function ConfirmDialog(props:OverlayProps) { return <Overlay {...props}>{props.children}</Overlay>; }
export function StatePanel({ state, title, description, action }: { state:"loading"|"empty"|"error"|"denied"|"readonly"|"locked"|"notFound"; title:string; description?:string; action?:ReactNode }) { const Icon = state === "error" ? AlertCircle : state === "locked" ? Lock : state === "denied" ? AlertCircle : Info; return <div className="v2-state" role={state === "error" ? "alert" : "status"}><Icon size={24} aria-hidden="true" /><h3>{title}</h3>{description ? <p>{description}</p> : null}{action}</div>; }
export function Skeleton({ height = 20 }: { height?:number }) { return <div className="v2-skeleton" style={{ height }} aria-hidden="true" />; }
