import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { teamApi, teamQueryKeys } from "../../../api/endpoints/team";
import { usersApi } from "../../../api/endpoints/users";
import { useAuthStore } from "../../../auth/authStore";
import { Button, ClickableRow, ConfirmDialog, DataTableShell, DetailHeader, Field, FormSection, PageHeaderV2, Pagination, SelectField, StatePanel, StatusBadge, StickyActionBar, SurfaceCard } from "../../../components/v2";
import { localizedEnum, teamUsersCopy } from "../../../features/teamUsers/i18n";
import type { RoleTransitionPreview } from "../../../types/team";
import type { UserCreatePayload, UserManagementRecord, UserUpdatePayload } from "../../../types/users";

type ApiProblem = { message?: string; details?: Record<string, string[] | string> };
const problem = (error: unknown): ApiProblem => typeof error === "object" && error !== null ? error as ApiProblem : {};
const message = (error: unknown, field?: string) => { const data = problem(error); const value = field ? data.details?.[field] : data.message; return Array.isArray(value) ? value.join(" ") : value; };
const label = (value: string) => value.split("_").map((part) => part[0] + part.slice(1).toLowerCase()).join(" ");
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const refresh = (client: ReturnType<typeof useQueryClient>, id?: number) => Promise.all([client.invalidateQueries({ queryKey: ["users"] }), client.invalidateQueries({ queryKey: teamQueryKeys.all }), ...(id ? [client.invalidateQueries({ queryKey: ["user", id] }), client.invalidateQueries({ queryKey: teamQueryKeys.detail(id) })] : [])]);

export function AdminUserListPage() {
  const navigate = useNavigate();
  const language = useAuthStore((state) => state.user?.language_preference ?? "EN");
  const c = teamUsersCopy(language);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [role, setRole] = useState("");
  const [status, setStatus] = useState("");
  const users = useQuery({ queryKey: ["users", page], queryFn: () => usersApi.list({ page }) });
  const filtered = (users.data?.results ?? []).filter((user) => {
    const matchesSearch = !search || `${user.full_name} ${user.email}`.toLowerCase().includes(search.toLowerCase());
    return matchesSearch && (!role || user.role === role) && (!status || (status === "ACTIVE") === user.is_active);
  });
  const clear = () => { setSearch(""); setRole(""); setStatus(""); };
  return <div className="admin-page users-access-page">
    <PageHeaderV2 title={c.usersAccess} description={c.usersDescription} action={<Link className="v2-button" to="/admin/users/new">{c.newAdmin}</Link>} />
    <SurfaceCard className="compact-toolbar-card users-filter-toolbar"><div className="v2-form-grid"><Field label={c.search} value={search} onChange={(event) => setSearch(event.target.value)} /><SelectField label={c.role} value={role} onChange={(event) => setRole(event.target.value)}><option value="">{c.allRoles}</option><option value="ADMIN">{c.admin}</option><option value="DOCTOR">{c.doctor}</option><option value="STAFF">{c.staff}</option></SelectField><SelectField label={c.loginStatus} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{c.allStatuses}</option><option value="ACTIVE">{c.active}</option><option value="INACTIVE">{c.inactive}</option></SelectField></div><Button type="button" compact variant="secondary" onClick={clear}>{c.clearFilters}</Button><small>{language === "AR" ? "\u062a\u0637\u0628\u0642 \u0639\u0648\u0627\u0645\u0644 \u0627\u0644\u062a\u0635\u0641\u064a\u0629 \u0639\u0644\u0649 \u0627\u0644\u0635\u0641\u062d\u0629 \u0627\u0644\u0645\u062d\u0645\u0644\u0629." : "Filters apply to the loaded page."}</small></SurfaceCard>
    {users.isLoading ? <StatePanel state="loading" title={c.loadingAccounts} /> : null}
    {users.isError && !users.data ? <StatePanel state="error" title={c.accountsUnavailable} action={<Button type="button" onClick={() => void users.refetch()}>{c.retry}</Button>} /> : null}
    {users.data ? <><DataTableShell title={c.accounts} count={users.data.count} toolbar={users.isFetching ? <span aria-live="polite">{c.refreshing}</span> : undefined}>{filtered.length ? <table className="users-identity-table"><thead><tr><th>{c.name}</th><th>{c.email}</th><th>{c.role}</th><th>{c.loginStatus}</th><th>{c.password}</th><th>{c.profile}</th><th>{c.created}</th><th /></tr></thead><tbody>{filtered.map((user) => <ClickableRow key={user.id} onOpen={() => navigate(`/admin/users/${user.id}`)}><td><div className="user-identity-cell"><span aria-hidden="true">{initials(user.full_name)}</span><strong>{user.full_name}</strong></div></td><td dir="ltr">{user.email}</td><td>{localizedEnum(language, user.role)}</td><td><StatusBadge status={user.is_active ? "ACTIVE" : "INACTIVE"} label={user.is_active ? c.active : c.inactive} /></td><td>{user.must_change_password ? c.mustChangePassword : c.passwordCurrent}</td><td>{localizedEnum(language, user.linked_profile_state)}</td><td>{formatDate(user.created_at)}</td></ClickableRow>)}</tbody></table> : <StatePanel state="empty" title={c.noAccounts} />}</DataTableShell><Pagination page={page} hasPrevious={Boolean(users.data.previous)} hasNext={Boolean(users.data.next)} onPrevious={() => setPage((value) => value - 1)} onNext={() => setPage((value) => value + 1)} labels={{ page: c.page, previous: c.previous, next: c.next }} /></> : null}
  </div>;
}

function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "U"; }

export function AdminNewUserPage() {
  const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const client = useQueryClient(); const [values, setValues] = useState({ full_name: "", email: "", temporary_password: "" }); const mutation = useMutation({ mutationFn: usersApi.create, onSuccess: async (user) => { await refresh(client); navigate(`/admin/users/${user.id}`); } }); const submit = (event: React.FormEvent) => { event.preventDefault(); mutation.mutate({ ...values, role: "ADMIN" }); };
  return <div className="admin-page"><PageHeaderV2 title={c.newAdminTitle} description={c.newAdminDescription} /><SurfaceCard major><form onSubmit={submit}><FormSection title={c.accountSection}><Field label={c.fullName} required value={values.full_name} error={message(mutation.error, "full_name")} onChange={(event) => setValues((current) => ({ ...current, full_name: event.target.value }))} /><Field label={c.email} type="email" required value={values.email} error={message(mutation.error, "email")} onChange={(event) => setValues((current) => ({ ...current, email: event.target.value }))} /><Field label={c.temporaryPassword} type="password" required value={values.temporary_password} error={message(mutation.error, "password") || message(mutation.error, "temporary_password")} onChange={(event) => setValues((current) => ({ ...current, temporary_password: event.target.value }))} /></FormSection>{message(mutation.error) ? <StatePanel state="error" title={message(mutation.error) ?? c.unableCreateAccount} /> : null}<StickyActionBar><Button type="submit" loading={mutation.isPending}>{c.createAdmin}</Button></StickyActionBar></form></SurfaceCard><p>{c.doctorStaffTeam} <Link to="/admin/team/new">{c.addTeamMember}</Link>.</p></div>;
}

function IdentityForm({ user }: { user: UserManagementRecord }) {
  const client = useQueryClient(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const [values, setValues] = useState<UserUpdatePayload>({ full_name: user.full_name, email: user.email }); const mutation = useMutation({ mutationFn: (payload: UserUpdatePayload) => usersApi.update(user.id, payload), onSuccess: () => void refresh(client, user.id) });
  return <SurfaceCard><form onSubmit={(event) => { event.preventDefault(); mutation.mutate(values); }}><FormSection title={c.accountIdentity}><Field label={c.fullName} required value={values.full_name ?? ""} error={message(mutation.error, "full_name")} onChange={(event) => setValues((current) => ({ ...current, full_name: event.target.value }))} /><Field label={c.email} type="email" required value={values.email ?? ""} error={message(mutation.error, "email")} onChange={(event) => setValues((current) => ({ ...current, email: event.target.value }))} /></FormSection>{message(mutation.error) ? <StatePanel state="error" title={message(mutation.error) ?? c.unableUpdateAccount} /> : null}<StickyActionBar><Button type="submit" loading={mutation.isPending}>{c.saveAccount}</Button></StickyActionBar></form></SurfaceCard>;
}

function RoleTransition({ user }: { user: UserManagementRecord }) {
  const client = useQueryClient(); const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const [target, setTarget] = useState(user.role); const [preview, setPreview] = useState<RoleTransitionPreview | null>(null); const [profile, setProfile] = useState({ specialty: "", position: "", phone: "", bio: "" }); const previewMutation = useMutation({ mutationFn: () => teamApi.previewRoleTransition(user.id, target), onSuccess: setPreview }); const confirmMutation = useMutation({ mutationFn: () => teamApi.confirmRoleTransition(user.id, { target_role: target, mode: "CONFIRM", confirmation_token: preview!.confirmation_token!, version: user.version, profile: target === "DOCTOR" ? { specialty: profile.specialty, phone: profile.phone, bio: profile.bio } : target === "STAFF" ? { position: profile.position, phone: profile.phone } : {} }), onSuccess: async (changed) => { await refresh(client, user.id); navigate(changed.team_member_id ? `/admin/team/${changed.team_member_id}` : `/admin/users/${changed.id}`); } });
  const changeTarget = (value: string) => { setTarget(value as UserManagementRecord["role"]); setPreview(null); };
  return <SurfaceCard><h3>{c.roleAccess}</h3><p>{c.roleDescription}</p><SelectField label={c.targetRole} value={target} onChange={(event) => changeTarget(event.target.value)}><option value="ADMIN">{c.admin}</option><option value="DOCTOR">{c.doctor}</option><option value="STAFF">{c.staff}</option></SelectField><Button type="button" variant="secondary" loading={previewMutation.isPending} disabled={target === user.role} onClick={() => previewMutation.mutate()}>{c.previewRole}</Button>{message(previewMutation.error) ? <StatePanel state="error" title={message(previewMutation.error) ?? c.transitionUnavailable} /> : null}{preview ? <div><p>{localizedEnum(language, preview.current_role)} → {localizedEnum(language, preview.target_role)}</p><p>{preview.consequences.join(" ")}</p><p>{c.operationalHistory}: {Object.entries(preview.operational_history).map(([key, value]) => `${localizedEnum(language, key)}: ${value}`).join(", ")}</p>{preview.blockers.map((blocker) => <p key={blocker.code} role="alert">{localizedEnum(language, blocker.code)}</p>)}{preview.allowed && preview.required_target_profile === "doctor_profile" ? <div className="v2-form-grid"><Field label={c.specialty} value={profile.specialty} onChange={(event) => setProfile((current) => ({ ...current, specialty: event.target.value }))} /><Field label={c.phone} value={profile.phone} onChange={(event) => setProfile((current) => ({ ...current, phone: event.target.value }))} /><label className="v2-field">{c.bio}<textarea value={profile.bio} onChange={(event) => setProfile((current) => ({ ...current, bio: event.target.value }))} /></label></div> : null}{preview.allowed && preview.required_target_profile === "staff_profile" ? <div className="v2-form-grid"><Field label={c.position} value={profile.position} onChange={(event) => setProfile((current) => ({ ...current, position: event.target.value }))} /><Field label={c.phone} value={profile.phone} onChange={(event) => setProfile((current) => ({ ...current, phone: event.target.value }))} /></div> : null}{preview.allowed ? <Button type="button" loading={confirmMutation.isPending} onClick={() => confirmMutation.mutate()}>{c.confirmRole}</Button> : null}{message(confirmMutation.error) ? <StatePanel state="error" title={message(confirmMutation.error) ?? c.transitionConfirmUnavailable} /> : null}</div> : null}</SurfaceCard>;
}

export function AdminUserDetailPage() {
  const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const client = useQueryClient(); const id = Number(useParams().userId); const [passwordOpen, setPasswordOpen] = useState(false); const [password, setPassword] = useState(""); const [activationOpen, setActivationOpen] = useState(false); const query = useQuery({ queryKey: ["user", id], queryFn: () => usersApi.detail(id), enabled: id > 0 }); const reset = useMutation({ mutationFn: () => usersApi.resetPassword(id, { temporary_password: password }), onSuccess: async () => { setPassword(""); setPasswordOpen(false); await refresh(client, id); } }); const activation = useMutation({ mutationFn: () => query.data!.is_active ? usersApi.deactivate(id) : usersApi.reactivate(id), onSuccess: async () => { setActivationOpen(false); await refresh(client, id); } });
  if (query.isLoading) return <StatePanel state="loading" title={c.loadingAccount} />; if (query.isError || !query.data) return <StatePanel state="notFound" title={c.accountUnavailable} action={<Button type="button" onClick={() => navigate("/admin/users")}>{c.backToUsers}</Button>} />; const user = query.data;
  return <div className="admin-page"><DetailHeader title={user.full_name} summary={c.usersDescription} /><IdentityForm key={`${user.id}-${user.updated_at}`} user={user} /><SurfaceCard><h3>{c.security}</h3><p>{user.must_change_password ? c.passwordRequiredDescription : c.passwordCurrentDescription}</p><Button type="button" variant="secondary" onClick={() => setPasswordOpen(true)}>{c.resetPassword}</Button></SurfaceCard><SurfaceCard><h3>{c.loginStatus}</h3><StatusBadge status={user.is_active ? "ACTIVE" : "INACTIVE"} label={user.is_active ? c.active : c.inactive} /><p>{c.loginStatusDescription}</p><Button type="button" variant="danger" onClick={() => setActivationOpen(true)}>{user.is_active ? c.deactivateAccount : c.reactivateAccount}</Button></SurfaceCard><SurfaceCard><h3>{c.linkedTeam}</h3><p>{localizedEnum(language, user.linked_profile_state)}</p>{user.team_member_id ? <Link className="v2-button secondary" to={`/admin/team/${user.team_member_id}`}>{c.openTeam}</Link> : null}{["PROFILE_SETUP_REQUIRED", "INCONSISTENT"].includes(user.linked_profile_state) ? <StatePanel state="locked" title={c.integrityWarning} description={c.integrityDescription} /> : null}</SurfaceCard><SurfaceCard><dl className="detail-grid"><div><dt>{c.created}</dt><dd>{formatDate(user.created_at)}</dd></div><div><dt>{c.updated}</dt><dd>{formatDate(user.updated_at)}</dd></div><div><dt>{c.accountVersion}</dt><dd>{user.version}</dd></div></dl></SurfaceCard><RoleTransition key={`${user.id}-${user.version}`} user={user} /><ConfirmDialog open={passwordOpen} title={c.resetPassword} description={c.resetDescription} pending={reset.isPending} onClose={() => { setPassword(""); setPasswordOpen(false); }}><Field label={c.temporaryPassword} type="password" value={password} error={message(reset.error, "temporary_password")} onChange={(event) => setPassword(event.target.value)} />{message(reset.error) ? <StatePanel state="error" title={message(reset.error) ?? c.resetUnavailable} /> : null}<Button disabled={!password} loading={reset.isPending} onClick={() => reset.mutate()}>{c.resetPassword}</Button><Button variant="secondary" disabled={reset.isPending} onClick={() => { setPassword(""); setPasswordOpen(false); }}>{c.cancel}</Button></ConfirmDialog><ConfirmDialog open={activationOpen} title={user.is_active ? c.deactivateAccount : c.reactivateAccount} description={c.accountAccessDescription} pending={activation.isPending} onClose={() => setActivationOpen(false)}><p>{user.is_active ? c.deactivateQuestion : c.reactivateQuestion}</p>{message(activation.error) ? <StatePanel state="error" title={message(activation.error) ?? c.accountAccessUnavailable} /> : null}<Button variant="danger" loading={activation.isPending} onClick={() => activation.mutate()}>{c.confirm}</Button><Button variant="secondary" disabled={activation.isPending} onClick={() => setActivationOpen(false)}>{c.cancel}</Button></ConfirmDialog></div>;
}
