"""Compatibility facade for scheduling domain services.

New code should import from the focused modules. Existing imports from this
module remain supported while each scheduling rule has one implementation.
"""

from apps.scheduling.appointment_services import (
    ACTIVE_COUNTING_STATUSES,
    LOCKED_EDIT_STATUSES,
    NEEDS_RESCHEDULE_SOURCE_STATUSES,
    RESCHEDULE_FIELDS,
    AppointmentRuleError,
    cancel_appointment,
    check_in_appointment,
    create_appointment,
    has_available_override,
    mark_appointment_no_show,
    require_version,
    transition_appointment,
    update_appointment,
    validate_appointment_slot,
    validate_capacity,
    validate_doctor_conflict,
    validate_duration,
    validate_start_not_past,
    validate_unavailable_exception,
    validate_working_hours,
)
from apps.scheduling.availability import (
    appointment_count_at,
    build_availability_slots,
    has_doctor_conflict,
    has_unavailable_exception,
)
from apps.scheduling.exception_services import (
    cancel_availability_exception,
    mark_overlapping_appointments_needs_reschedule,
    save_availability_exception,
    update_availability_exception,
)
from apps.scheduling.schedule_services import (
    ShiftSpec,
    _apply_schedule,
    _schedule_rows,
    apply_default_schedule,
    copy_employee_schedule,
    create_working_shift,
    replace_employee_schedule,
    save_default_shift,
    set_default_shift_active,
    set_working_shift_active,
    update_default_shift,
    update_working_shift,
    validate_shift_overlap,
)
from apps.scheduling.time_utils import (
    calculate_end_datetime,
    clinic_localtime,
    clinic_now,
    get_clinic_settings,
    get_clinic_timezone,
)


__all__ = [
    "ACTIVE_COUNTING_STATUSES",
    "LOCKED_EDIT_STATUSES",
    "NEEDS_RESCHEDULE_SOURCE_STATUSES",
    "RESCHEDULE_FIELDS",
    "AppointmentRuleError",
    "ShiftSpec",
    "_apply_schedule",
    "_schedule_rows",
    "appointment_count_at",
    "apply_default_schedule",
    "build_availability_slots",
    "calculate_end_datetime",
    "cancel_appointment",
    "cancel_availability_exception",
    "check_in_appointment",
    "clinic_localtime",
    "clinic_now",
    "copy_employee_schedule",
    "create_appointment",
    "create_working_shift",
    "get_clinic_settings",
    "get_clinic_timezone",
    "has_available_override",
    "has_doctor_conflict",
    "has_unavailable_exception",
    "mark_appointment_no_show",
    "mark_overlapping_appointments_needs_reschedule",
    "replace_employee_schedule",
    "require_version",
    "save_availability_exception",
    "save_default_shift",
    "set_default_shift_active",
    "set_working_shift_active",
    "transition_appointment",
    "update_appointment",
    "update_availability_exception",
    "update_default_shift",
    "update_working_shift",
    "validate_appointment_slot",
    "validate_capacity",
    "validate_doctor_conflict",
    "validate_duration",
    "validate_shift_overlap",
    "validate_start_not_past",
    "validate_unavailable_exception",
    "validate_working_hours",
]
