import type { LanguagePreference } from "../../types/auth";

const copy = {
  EN: {
    activeVisit: "Active visit", visitDetails: "Visit details", activeVisitDescription: "Document the current clinical encounter and complete it when care is finished.", visitDetailsDescription: "Review the appointment context and clinical documentation for this visit.", loadingActive: "Loading active visit...", loadingDetails: "Loading visit details...", loadActiveError: "Unable to load active visit", loadDetailsError: "Unable to load visit details", noActive: "No active visit", noActiveDescription: "Start a checked-in appointment to begin documenting a visit.", openAppointments: "Open appointments",
    visitNotes: "Visit Notes", patientProfile: "Patient Profile", attachments: "X-rays / Attachments", billing: "Billing / Invoice Handoff", patient: "Patient", doctor: "Doctor", appointment: "Appointment", reason: "Reason", started: "Started", completed: "Completed", status: "Status", phone: "Phone", age: "Age", gender: "Gender", medicalHistory: "Medical Conditions History", bloodGroup: "Blood group", insurance: "Insurance", notRecorded: "—", openPatient: "Open full patient profile", patientContext: "Read-first clinical context. Edit is available only in the full authorized patient workspace.", clinicalNotes: "Clinical notes", notesDescription: "Record the clinical encounter. Completed visits remain editable only for the owning doctor.", notesReadOnly: "Clinical notes are read-only for your role and this visit.", notesSaved: "Notes saved.", conflictTitle: "This visit was updated elsewhere", conflictDescription: "Refresh the visit to review the latest clinical notes before saving again.", refreshVisit: "Refresh visit", completeVisit: "Complete Visit", completeDescription: "Finish this encounter after confirming the clinical notes are ready.", finalizing: "Finalizing visit", visitSummary: "Patient and visit summary", appointmentStatus: "Appointment status", visitStatus: "Visit status", saveNotes: "Save Notes", saving: "Saving...", saveError: "Unable to save clinical notes. Review the entries and try again.", symptoms: "Symptoms", diagnosis: "Diagnosis", treatment: "Treatment", followUp: "Follow-up notes", clinicalNotesField: "Clinical notes", workflow: "Clinical workflow", completeConfirm: "Complete visit", completeQuestion: "Mark the active visit for {patient} as completed? This also completes the linked appointment.", unsaved: "Unsaved clinical notes will be saved before the visit is completed.", completeError: "Unable to complete visit", keepActive: "Keep visit active", saveAndComplete: "Save & Complete", completing: "Completing...",
    xraysTitle: "X-rays", xraysDescription: "Protected X-rays linked to this visit.", uploadVisitXray: "Upload visit X-ray", loadingXrays: "Loading visit X-rays...", loadXraysError: "Unable to load visit X-rays", noXrays: "No X-rays are linked to this visit.", aiResultAvailable: "Stored AI result available", noAiResult: "No stored AI result", billingTitle: "Billing handoff", billingEligible: "Send this completed visit to Staff billing when it is ready.", billingVisibility: "Billing handoff visibility follows your backend role permissions.", createBillingHandoff: "Send to Billing", loadBillingError: "Unable to load billing handoff", billingStatus: "Handoff status", email: "Email", emergencyContact: "Emergency contact", address: "Address", generalNotes: "General notes", created: "Created", updated: "Last updated", yearsOld: "years old", unsavedProfileConfirm: "You have unsaved visit notes. Open the full patient profile and discard those edits?",
  },
  AR: {
    activeVisit: "الزيارة النشطة", visitDetails: "تفاصيل الزيارة", activeVisitDescription: "وثّق المقابلة السريرية الحالية وأكملها عند انتهاء الرعاية.", visitDetailsDescription: "راجع سياق الموعد والتوثيق السريري لهذه الزيارة.", loadingActive: "جارٍ تحميل الزيارة النشطة...", loadingDetails: "جارٍ تحميل تفاصيل الزيارة...", loadActiveError: "تعذر تحميل الزيارة النشطة", loadDetailsError: "تعذر تحميل تفاصيل الزيارة", noActive: "لا توجد زيارة نشطة", noActiveDescription: "ابدأ موعداً تم تسجيل حضوره لبدء التوثيق.", openAppointments: "فتح المواعيد",
    visitNotes: "ملاحظات الزيارة", patientProfile: "ملف المريض", attachments: "الأشعة والمرفقات", billing: "تسليم الفوترة والفاتورة", patient: "المريض", doctor: "الطبيب", appointment: "الموعد", reason: "السبب", started: "بدأت", completed: "اكتملت", status: "الحالة", phone: "الهاتف", age: "العمر", gender: "الجنس", medicalHistory: "التاريخ المرضي", bloodGroup: "فصيلة الدم", insurance: "التأمين", notRecorded: "—", openPatient: "فتح ملف المريض الكامل", patientContext: "سياق سريري للقراءة أولاً. التعديل متاح فقط في مساحة عمل المريض المصرح بها.", clinicalNotes: "الملاحظات السريرية", notesDescription: "وثّق المقابلة السريرية. تبقى الزيارات المكتملة قابلة للتعديل للطبيب المالك فقط.", notesReadOnly: "الملاحظات السريرية للقراءة فقط لدورك وهذه الزيارة.", notesSaved: "تم حفظ الملاحظات.", conflictTitle: "تم تحديث هذه الزيارة في مكان آخر", conflictDescription: "حدّث الزيارة لمراجعة أحدث الملاحظات قبل الحفظ مرة أخرى.", refreshVisit: "تحديث الزيارة", completeVisit: "إكمال الزيارة", completeDescription: "أنهَ هذه المقابلة بعد تأكيد جاهزية الملاحظات السريرية.", finalizing: "إنهاء الزيارة", visitSummary: "ملخص المريض والزيارة", appointmentStatus: "حالة الموعد", visitStatus: "حالة الزيارة", saveNotes: "حفظ الملاحظات", saving: "جارٍ الحفظ...", saveError: "تعذر حفظ الملاحظات السريرية. راجع المدخلات وحاول مجدداً.", symptoms: "الأعراض", diagnosis: "التشخيص", treatment: "العلاج", followUp: "ملاحظات المتابعة", clinicalNotesField: "الملاحظات السريرية", workflow: "سير العمل السريري", completeConfirm: "إكمال الزيارة", completeQuestion: "هل تريد وضع الزيارة النشطة لـ {patient} كمكتملة؟ سيكتمل الموعد المرتبط أيضاً.", unsaved: "سيتم حفظ الملاحظات السريرية غير المحفوظة قبل إكمال الزيارة.", completeError: "تعذر إكمال الزيارة", keepActive: "إبقاء الزيارة نشطة", saveAndComplete: "حفظ وإكمال", completing: "جارٍ الإكمال...",
    xraysTitle: "الأشعة", xraysDescription: "أشعة محمية مرتبطة بهذه الزيارة.", uploadVisitXray: "رفع أشعة للزيارة", loadingXrays: "جارٍ تحميل أشعة الزيارة...", loadXraysError: "تعذر تحميل أشعة الزيارة", noXrays: "لا توجد أشعة مرتبطة بهذه الزيارة.", aiResultAvailable: "تتوفر نتيجة ذكاء اصطناعي محفوظة", noAiResult: "لا توجد نتيجة ذكاء اصطناعي محفوظة", billingTitle: "تسليم الفوترة", billingEligible: "أرسل هذه الزيارة المكتملة إلى فوترة الموظفين عندما تصبح جاهزة.", billingVisibility: "تتبع رؤية تسليم الفوترة صلاحيات دورك في الخلفية.", createBillingHandoff: "إرسال إلى الفوترة", loadBillingError: "تعذر تحميل تسليم الفوترة", billingStatus: "حالة التسليم", email: "البريد الإلكتروني", emergencyContact: "جهة اتصال الطوارئ", address: "العنوان", generalNotes: "ملاحظات عامة", created: "تاريخ الإنشاء", updated: "آخر تحديث", yearsOld: "سنة", unsavedProfileConfirm: "لديك ملاحظات زيارة غير محفوظة. هل تريد فتح ملف المريض الكامل وتجاهل هذه التعديلات؟",
  },
} as const;

export type VisitCopy = { [Key in keyof typeof copy.EN]: string };
export const visitCopy = (language: LanguagePreference = "EN"): VisitCopy => copy[language];
