# Generated by Django 6.0.7 on 2026-07-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_activ_action_f3dbf7_idx'), models.Index(fields=['actor', 'created_at'], name='audit_activ_actor_i_5122be_idx'), models.Index(fields=['actor_role', 'created_at'], name='audit_activ_actor_r_d4cd16_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_activ_entity__5a526e_idx'), models.Index(fields=['created_at'], name='audit_activ_created_7a5871_idx')],
            },
        ),
    ]
