import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { teamApi, teamQueryKeys } from "../../../api/endpoints/team";
import { useAuthStore } from "../../../auth/authStore";
import { Button, ClickableRow, ConfirmDialog, DataTableShell, DetailHeader, Field, FormSection, PageHeaderV2, Pagination, SelectField, StatePanel, StatusBadge, StickyActionBar, SurfaceCard } from "../../../components/v2";
import { localizedEnum, teamUsersCopy } from "../../../features/teamUsers/i18n";
import type { TeamMemberCreatePayload, TeamMemberDetail, TeamMemberUpdatePayload } from "../../../types/team";

type ApiProblem = { message?: string; details?: Record<string, string[] | string> };
const problem = (error: unknown): ApiProblem => typeof error === "object" && error !== null ? error as ApiProblem : {};
const errorText = (error: unknown, field?: string) => {
  const data = problem(error); const value = field ? data.details?.[field] : data.message;
  return Array.isArray(value) ? value.join(" ") : value;
};
const label = (value: string) => value.split("_").map((part) => part[0] + part.slice(1).toLowerCase()).join(" ");
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const invalidate = (client: ReturnType<typeof useQueryClient>) => Promise.all([client.invalidateQueries({ queryKey: teamQueryKeys.all }), client.invalidateQueries({ queryKey: ["users"] })]);

export function TeamListPage() {
  const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [role, setRole] = useState(""); const [professionalStatus, setProfessionalStatus] = useState(""); const [availability, setAvailability] = useState("");
  const query = useQuery({ queryKey: [...teamQueryKeys.all, { page, q, role, professionalStatus, availability }], queryFn: () => teamApi.list({ page, ...(q ? { q } : {}), ...(role ? { role } : {}), ...(professionalStatus ? { professional_status: professionalStatus } : {}), ...(availability ? { availability } : {}) }) });
  const clear = () => { setPage(1); setQ(""); setRole(""); setProfessionalStatus(""); setAvailability(""); };
  return <div className="admin-page"><PageHeaderV2 title={c.team} description={c.teamDescription} action={<Link className="v2-button" to="/admin/team/new">{c.addTeamMember}</Link>} />
    <SurfaceCard><div className="v2-form-grid"><Field label={c.search} value={q} onChange={(event) => { setPage(1); setQ(event.target.value); }} placeholder={c.searchPlaceholder} /><SelectField label={c.role} value={role} onChange={(event) => { setPage(1); setRole(event.target.value); }}><option value="">{c.allRoles}</option><option value="DOCTOR">{c.doctor}</option><option value="STAFF">{c.staff}</option></SelectField><SelectField label={c.professionalStatus} value={professionalStatus} onChange={(event) => { setPage(1); setProfessionalStatus(event.target.value); }}><option value="">{c.allStatuses}</option><option value="ACTIVE">{c.active}</option><option value="INACTIVE">{c.inactive}</option></SelectField><SelectField label={c.availability} value={availability} onChange={(event) => { setPage(1); setAvailability(event.target.value); }}><option value="">{c.allAvailability}</option><option value="AVAILABLE">{c.available}</option><option value="ON_LEAVE">{c.onLeave}</option><option value="UNAVAILABLE">{c.unavailable}</option></SelectField></div><Button type="button" compact variant="secondary" onClick={clear}>{c.clearFilters}</Button></SurfaceCard>
    {query.isLoading ? <StatePanel state="loading" title={c.loadingTeam} /> : null}{query.isError && !query.data ? <StatePanel state="error" title={c.teamUnavailable} action={<Button type="button" onClick={() => void query.refetch()}>{c.retry}</Button>} /> : null}
    {query.data ? <><DataTableShell title={c.teamMembers} count={query.data.count} toolbar={query.isFetching ? <span aria-live="polite">{c.refreshing}</span> : undefined}>{query.data.results.length ? <table><thead><tr><th>{c.name}</th><th>{c.role}</th><th>{c.professionalStatus}</th><th>{c.account}</th><th>{c.availability}</th><th>{c.today}</th><th /></tr></thead><tbody>{query.data.results.map((member) => <ClickableRow key={member.id} onOpen={() => navigate(`/admin/team/${member.id}`)}><td><strong>{member.full_name}</strong><br /><small>{member.role === "DOCTOR" ? member.specialty || c.noSpecialty : member.position || c.noPosition}</small></td><td>{localizedEnum(language, member.role)}</td><td><StatusBadge status={localizedEnum(language, member.professional_status)} /></td><td><StatusBadge status={member.account.is_active ? c.active : c.inactive} /></td><td>{localizedEnum(language, member.availability.availability)}</td><td>{member.today_workload.appointment_count} {c.appointments} · {member.today_workload.active_visit_count} {c.activeVisits}</td></ClickableRow>)}</tbody></table> : <StatePanel state="empty" title={c.noTeamMembers} />}</DataTableShell><Pagination page={page} hasPrevious={Boolean(query.data.previous)} hasNext={Boolean(query.data.next)} onPrevious={() => setPage((value) => value - 1)} onNext={() => setPage((value) => value + 1)} labels={{ page: c.page, previous: c.previous, next: c.next }} /></> : null}</div>;
}

export function TeamNewPage() {
  const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const client = useQueryClient(); const [role, setRole] = useState<"DOCTOR" | "STAFF">("DOCTOR"); const [values, setValues] = useState({ full_name: "", email: "", temporary_password: "", specialty: "", position: "", phone: "", bio: "" });
  const mutation = useMutation({ mutationFn: teamApi.create, onSuccess: async (member) => { await invalidate(client); navigate(`/admin/team/${member.id}`); } });
  const submit = (event: React.FormEvent) => { event.preventDefault(); const account = { full_name: values.full_name, email: values.email, temporary_password: values.temporary_password }; const payload: TeamMemberCreatePayload = role === "DOCTOR" ? { account, role, doctor_profile: { specialty: values.specialty, phone: values.phone, bio: values.bio } } : { account, role, staff_profile: { position: values.position, phone: values.phone } }; mutation.mutate(payload); };
  const set = (key: keyof typeof values) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValues((current) => ({ ...current, [key]: event.target.value }));
  return <div className="admin-page"><PageHeaderV2 title={c.addTitle} description={c.addDescription} /><SurfaceCard major><form onSubmit={submit}><FormSection title={c.accountSection}><Field label={c.fullName} required value={values.full_name} error={errorText(mutation.error, "account") || errorText(mutation.error, "full_name")} onChange={set("full_name")} /><Field label={c.email} type="email" required value={values.email} error={errorText(mutation.error, "email")} onChange={set("email")} /><Field label={c.temporaryPassword} type="password" required value={values.temporary_password} error={errorText(mutation.error, "temporary_password")} onChange={set("temporary_password")} /></FormSection><FormSection title={c.professionalProfile}><SelectField label={c.role} value={role} onChange={(event) => setRole(event.target.value as "DOCTOR" | "STAFF")}><option value="DOCTOR">{c.doctor}</option><option value="STAFF">{c.staff}</option></SelectField>{role === "DOCTOR" ? <><Field label={c.specialty} value={values.specialty} error={errorText(mutation.error, "doctor_profile")} onChange={set("specialty")} /><Field label={c.phone} value={values.phone} onChange={set("phone")} /><label className="v2-field">{c.bio}<textarea value={values.bio} onChange={set("bio")} /></label></> : <><Field label={c.position} value={values.position} error={errorText(mutation.error, "staff_profile")} onChange={set("position")} /><Field label={c.phone} value={values.phone} onChange={set("phone")} /></>}</FormSection>{errorText(mutation.error) ? <StatePanel state="error" title={errorText(mutation.error) ?? c.unableCreateTeam} /> : null}<StickyActionBar><Button type="submit" loading={mutation.isPending}>{c.createTeamMember}</Button></StickyActionBar></form></SurfaceCard></div>;
}

function TeamProfileForm({ member }: { member: TeamMemberDetail }) {
  const client = useQueryClient(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const id = member.id; const [values, setValues] = useState({ specialty: "specialty" in member.profile ? member.profile.specialty : "", position: "position" in member.profile ? member.profile.position : "", phone: member.profile.phone, bio: "bio" in member.profile ? member.profile.bio : "" }); const [conflict, setConflict] = useState(false);
  const mutation = useMutation({ mutationFn: (payload: TeamMemberUpdatePayload) => teamApi.update(id, payload), onSuccess: async () => { setConflict(false); await Promise.all([client.invalidateQueries({ queryKey: teamQueryKeys.detail(id) }), invalidate(client)]); }, onError: (error) => { if (problem(error).message?.includes("changed")) setConflict(true); } });
  const reload = () => { setConflict(false); void client.invalidateQueries({ queryKey: teamQueryKeys.detail(id) }); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); mutation.mutate(member.role === "DOCTOR" ? { specialty: values.specialty, phone: values.phone, bio: values.bio, version: member.version } : { position: values.position, phone: values.phone, version: member.version }); };
  return <SurfaceCard><form onSubmit={submit}><FormSection title={c.professionalInformation}>{member.role === "DOCTOR" ? <><Field label={c.specialty} value={values.specialty} onChange={(event) => setValues((current) => ({ ...current, specialty: event.target.value }))} /><Field label={c.phone} value={values.phone} onChange={(event) => setValues((current) => ({ ...current, phone: event.target.value }))} /><label className="v2-field">{c.bio}<textarea value={values.bio} onChange={(event) => setValues((current) => ({ ...current, bio: event.target.value }))} /></label></> : <><Field label={c.position} value={values.position} onChange={(event) => setValues((current) => ({ ...current, position: event.target.value }))} /><Field label={c.phone} value={values.phone} onChange={(event) => setValues((current) => ({ ...current, phone: event.target.value }))} /></>}</FormSection>{conflict ? <StatePanel state="locked" title={c.profileChanged} action={<Button type="button" variant="secondary" onClick={reload}>{c.reloadLatest}</Button>} /> : null}<StickyActionBar><Button type="submit" loading={mutation.isPending}>{c.saveProfessional}</Button></StickyActionBar></form></SurfaceCard>;
}

export function TeamDetailPage() {
  const navigate = useNavigate(); const language = useAuthStore((state) => state.user?.language_preference ?? "EN"); const c = teamUsersCopy(language); const id = Number(useParams().teamMemberId); const client = useQueryClient(); const [confirmStatus, setConfirmStatus] = useState(false); const query = useQuery({ queryKey: teamQueryKeys.detail(id), queryFn: () => teamApi.detail(id), enabled: id > 0 }); const status = useMutation({ mutationFn: (active: boolean) => teamApi.setProfessionalStatus(id, { is_active: active, version: query.data!.version }), onSuccess: async () => { setConfirmStatus(false); await Promise.all([client.invalidateQueries({ queryKey: teamQueryKeys.detail(id) }), invalidate(client)]); } });
  if (query.isLoading) return <StatePanel state="loading" title={c.loadingTeam} />; if (query.isError || !query.data) return <StatePanel state="notFound" title={c.teamUnavailable} action={<Button type="button" onClick={() => navigate("/admin/team")}>{c.backToTeam}</Button>} />; const member = query.data;
  return <div className="admin-page"><DetailHeader title={member.full_name} summary={`${localizedEnum(language, member.role)} ${c.professionalProfileSummary}`} action={<Link className="v2-button secondary" to={`/admin/users/${member.account.id}`}>{c.openUsers}</Link>} /><SurfaceCard><dl className="detail-grid"><div><dt>{c.role}</dt><dd>{localizedEnum(language, member.role)}</dd></div><div><dt>{c.professionalStatus}</dt><dd><StatusBadge status={localizedEnum(language, member.professional_status)} /></dd></div><div><dt>{c.loginAccount}</dt><dd dir="ltr">{member.account.email}<br /><StatusBadge status={member.account.is_active ? c.active : c.inactive} /></dd></div><div><dt>{c.passwordState}</dt><dd>{member.account.must_change_password ? c.mustChangePassword : c.passwordCurrent}</dd></div><div><dt>{c.availability}</dt><dd>{localizedEnum(language, member.availability.availability)}</dd></div><div><dt>{c.workloadToday}</dt><dd>{member.today_workload.appointment_count} {c.appointments} · {member.today_workload.active_visit_count} {c.activeVisits}</dd></div></dl><Button type="button" variant="danger" onClick={() => setConfirmStatus(true)}>{member.professional_status === "ACTIVE" ? c.deactivateProfessional : c.reactivateProfessional}</Button></SurfaceCard><TeamProfileForm key={`${member.id}-${member.version}`} member={member} /><SurfaceCard><h3>{c.workingHours}</h3>{member.active_shifts.length ? <ul>{member.active_shifts.map((shift) => <li key={shift.id}>{shift.name}: {shift.weekday}, {shift.start_time}–{shift.end_time}</li>)}</ul> : <p>{c.noWorkingHours}</p>}<h3>{c.leaveExceptions}</h3>{member.current_future_leave.length ? <ul>{member.current_future_leave.map((leave) => <li key={leave.id}>{formatDate(leave.start_datetime)} – {formatDate(leave.end_datetime)}{leave.reason ? `: ${leave.reason}` : ""}</li>)}</ul> : <p>{c.noLeave}</p>}</SurfaceCard><ConfirmDialog open={confirmStatus} title={c.confirmProfessionalStatus} description={c.professionalStatusDescription} pending={status.isPending} onClose={() => setConfirmStatus(false)}><p>{member.professional_status === "ACTIVE" ? c.deactivateProfessionalQuestion : c.reactivateProfessionalQuestion}</p>{status.error ? <StatePanel state="error" title={errorText(status.error) ?? c.teamUnavailable} /> : null}<Button variant="danger" loading={status.isPending} onClick={() => status.mutate(member.professional_status !== "ACTIVE")}>{c.confirm}</Button><Button variant="secondary" disabled={status.isPending} onClick={() => setConfirmStatus(false)}>{c.cancel}</Button></ConfirmDialog></div>;
}
