import type { LanguagePreference } from "../../types/auth";

const copy = {
  EN: {
    patients: "Patients", patientDirectory: "Patient directory", patientDirectoryDescription: "Search and manage patient records according to your role.", newPatient: "New patient", search: "Search", searchPlaceholder: "Search by name, phone, email, or ID", archiveState: "Archive state", active: "Active", archived: "Archived", clearFilters: "Clear filters", refresh: "Refreshing patient results…", loading: "Loading patients…", loadError: "Unable to load patients", retry: "Retry", noPatients: "No patients found for this filter.", records: "records", previous: "Previous", next: "Next", page: "Page", patient: "Patient", contact: "Contact", gender: "Gender", age: "Age", status: "Status", actions: "Actions", view: "View", edit: "Edit", archive: "Archive", reactivate: "Reactivate", notRecorded: "Not recorded", overview: "Overview", medicalHistory: "Medical Summary", visits: "Visits", appointments: "Appointments", xraysAi: "X-rays & AI", billing: "Billing/Handoff", backToPatients: "Back to patients", patientProfile: "Patient profile", yearsOld: "years old", identity: "Identity", generalInformation: "General information", contactDetails: "Contact details", clinicalProfile: "Clinical profile", firstName: "First name", lastName: "Last name", dateOfBirth: "Date of birth", phone: "Phone", email: "Email", nationalId: "National ID or passport", emergencyContact: "Emergency contact", address: "Address", bloodGroup: "Blood group", medicalConditions: "Medical conditions history", insurance: "Insurance information", generalNotes: "General notes", save: "Save patient", saving: "Saving…", cancel: "Cancel", createPatient: "Create patient", saveChanges: "Save changes", editPatient: "Edit patient", noMedicalHistory: "No medical history has been recorded.", noInsurance: "No insurance information has been recorded.", noNotes: "No general notes have been recorded.", updated: "Updated", created: "Created", version: "Version", createdBy: "Created by", updatedBy: "Updated by", archivePatient: "Archive patient", reactivatePatient: "Reactivate patient", archiveDescription: "Archived patients are hidden from active lists and cannot be selected for new appointments. Their record remains stored.", reactivateDescription: "This patient will return to active patient lists.", conflict: "This patient was changed elsewhere. Reload the latest record before saving over it.", continueReviewing: "Continue reviewing my changes", reloadLatest: "Reload latest record", staffOnlyNote: "Doctors can update patient profile fields for active patients only. Archive controls are hidden.", missingPatient: "Patient was not found or is unavailable to this role.", required: "Required", female: "Female", male: "Male", noBloodGroup: "Not recorded",
  },
  AR: {
    patients: "المرضى", patientDirectory: "دليل المرضى", patientDirectoryDescription: "ابحث عن سجلات المرضى وأدرها وفقاً لدورك.", newPatient: "مريض جديد", search: "بحث", searchPlaceholder: "ابحث بالاسم أو الهاتف أو البريد أو المعرّف", archiveState: "حالة السجل", active: "نشط", archived: "مؤرشف", clearFilters: "مسح عوامل التصفية", refresh: "يتم تحديث نتائج المرضى…", loading: "يتم تحميل المرضى…", loadError: "تعذر تحميل المرضى", retry: "إعادة المحاولة", noPatients: "لا يوجد مرضى لهذا التصفية.", records: "سجلات", previous: "السابق", next: "التالي", page: "الصفحة", patient: "المريض", contact: "التواصل", gender: "الجنس", age: "العمر", status: "الحالة", actions: "الإجراءات", view: "عرض", edit: "تعديل", archive: "أرشفة", reactivate: "إعادة التفعيل", notRecorded: "غير مسجل", overview: "نظرة عامة", medicalHistory: "التاريخ الطبي", visits: "الزيارات", appointments: "المواعيد", xraysAi: "الأشعة والذكاء الاصطناعي", billing: "الفواتير", backToPatients: "العودة إلى المرضى", patientProfile: "ملف المريض", yearsOld: "سنة", identity: "الهوية", generalInformation: "المعلومات العامة", contactDetails: "بيانات التواصل", clinicalProfile: "الملف السريري", firstName: "الاسم الأول", lastName: "اسم العائلة", dateOfBirth: "تاريخ الميلاد", phone: "الهاتف", email: "البريد الإلكتروني", nationalId: "الهوية الوطنية أو جواز السفر", emergencyContact: "جهة اتصال للطوارئ", address: "العنوان", bloodGroup: "فصيلة الدم", medicalConditions: "التاريخ المرضي", insurance: "معلومات التأمين", generalNotes: "ملاحظات عامة", save: "حفظ", saving: "جارٍ الحفظ…", cancel: "إلغاء", createPatient: "إنشاء مريض", saveChanges: "حفظ التغييرات", editPatient: "تعديل المريض", noMedicalHistory: "لا يوجد تاريخ طبي مسجل.", noInsurance: "لا توجد معلومات تأمين مسجلة.", noNotes: "لا توجد ملاحظات عامة مسجلة.", updated: "آخر تحديث", created: "تاريخ الإنشاء", version: "الإصدار", createdBy: "أنشئ بواسطة", updatedBy: "حُدّث بواسطة", archivePatient: "أرشفة المريض", reactivatePatient: "إعادة تفعيل المريض", archiveDescription: "يُخفى المرضى المؤرشفون من القوائم النشطة ولا يمكن اختيارهم للمواعيد الجديدة، مع الاحتفاظ بالسجل.", reactivateDescription: "سيعود هذا المريض إلى قوائم المرضى النشطة.", conflict: "عُدل هذا المريض في مكان آخر. أعد تحميل أحدث سجل قبل الحفظ.", reloadLatest: "إعادة تحميل أحدث سجل", continueReviewing: "متابعة مراجعة التغييرات", staffOnlyNote: "يمكن للموظفين فقط إنشاء سجلات المرضى أو أرشفتها أو إعادة تفعيلها.", missingPatient: "لم يتم العثور على المريض أو أنه غير متاح لهذا الدور.", required: "مطلوب", female: "أنثى", male: "ذكر", noBloodGroup: "غير مسجل",
  },
} as const;

export type PatientCopy = Record<keyof typeof copy.EN, string>;

export function patientCopy(language: LanguagePreference | string | undefined): PatientCopy {
  return copy[language === "AR" ? "AR" : "EN"];
}
