# Generated by Django 6.0.7 on 2026-07-08 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('medical_summary', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'indexes': [models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'), models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'), models.Index(fields=['is_archived'], name='patients_pa_is_arch_b8e241_idx')],
            },
        ),
    ]
