# Generated by Django 6.0.7 on 2026-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password_user_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
