import type { LanguagePreference } from "../../types/auth";

const en = {
  team: "Team", usersAccess: "Users & Access", addTeamMember: "Add team member", newAdmin: "New Admin account", teamDescription: "Professional Doctor and Staff directory.", usersDescription: "Login accounts, security state, and protected access transitions.",
  search: "Search", searchPlaceholder: "Name or email", role: "Role", allRoles: "All roles", doctor: "Doctor", staff: "Staff", admin: "Admin", professionalStatus: "Professional status", allStatuses: "All statuses", active: "Active", inactive: "Inactive", availability: "Availability", allAvailability: "All availability", available: "Available", onLeave: "On leave", unavailable: "Unavailable", clearFilters: "Clear filters", loadingTeam: "Loading team members", teamUnavailable: "Team members are unavailable", retry: "Retry", refreshing: "Refreshing…", teamMembers: "Team members", noTeamMembers: "No team members match these filters", name: "Name", account: "Account", today: "Today", noSpecialty: "No specialty", noPosition: "No position", appointments: "appointments", activeVisits: "active visits", previous: "Previous", next: "Next", page: "Page",
  addTitle: "Add team member", addDescription: "Creates a login account and matching professional profile together.", accountSection: "Account", fullName: "Full name", email: "Email", temporaryPassword: "Temporary password", professionalProfile: "Professional profile", specialty: "Specialty", phone: "Phone", bio: "Bio", position: "Position", createTeamMember: "Create team member", unableCreateTeam: "Unable to create team member",
  openUsers: "Open Users & Access", professionalProfileSummary: "professional profile", loginAccount: "Login account", passwordState: "Password state", passwordCurrent: "Password current", mustChangePassword: "Must change password", workloadToday: "Workload today", deactivateProfessional: "Deactivate professional profile", reactivateProfessional: "Reactivate professional profile", professionalInformation: "Professional information", profileChanged: "This profile changed elsewhere. Your edits are still here.", reloadLatest: "Reload latest record", saveProfessional: "Save professional profile", workingHours: "Working hours", noWorkingHours: "No active working hours returned.", leaveExceptions: "Leave exceptions", noLeave: "No current or future leave returned.", confirmProfessionalStatus: "Confirm professional status", professionalStatusDescription: "Professional availability is separate from login account access.", deactivateProfessionalQuestion: "Deactivate this professional profile? The login account remains unchanged.", reactivateProfessionalQuestion: "Reactivate this professional profile? The login account remains unchanged.", confirm: "Confirm", cancel: "Cancel", backToTeam: "Back to Team",
  loadingAccounts: "Loading accounts", accountsUnavailable: "Accounts are unavailable", accounts: "Accounts", password: "Password", profile: "Profile", updated: "Updated", noAccounts: "No accounts returned", newAdminTitle: "New Admin account", newAdminDescription: "Doctor and Staff onboarding is managed from Team.", createAdmin: "Create Admin account", doctorStaffTeam: "To onboard a Doctor or Staff member, use Add team member.", unableCreateAccount: "Unable to create account", accountIdentity: "Account identity", saveAccount: "Save account", unableUpdateAccount: "Unable to update account", security: "Security", passwordCurrentDescription: "Password is current.", passwordRequiredDescription: "The user must change their password at next sign-in.", resetPassword: "Reset temporary password", loginStatus: "Login status", loginStatusDescription: "Login access is separate from any professional profile status.", deactivateAccount: "Deactivate account", reactivateAccount: "Reactivate account", linkedTeam: "Linked Team profile", openTeam: "Open Team profile", integrityWarning: "Professional profile integrity needs attention", integrityDescription: "This account cannot be represented as a Team member until backend linkage is consistent.", created: "Created", accountVersion: "Account version", loadingAccount: "Loading account", accountUnavailable: "Account unavailable", backToUsers: "Back to Users & Access",
  roleAccess: "Role and access", roleDescription: "Role changes affect workspace access and professional linkage. They require a server preview and confirmation.", targetRole: "Target role", previewRole: "Preview role transition", operationalHistory: "Operational history", confirmRole: "Confirm protected role transition", transitionUnavailable: "Unable to preview transition", transitionConfirmUnavailable: "Unable to confirm transition", resetDescription: "The password is not retained after submission.", resetUnavailable: "Unable to reset password", deactivateQuestion: "Deactivate this login account?", reactivateQuestion: "Reactivate this login account?", accountAccessDescription: "Account access is separate from professional availability.", accountAccessUnavailable: "Unable to update login access",
} as const;

type TeamUsersCopy = { [Key in keyof typeof en]: string };
const ar: TeamUsersCopy = {
  team: "الفريق", usersAccess: "المستخدمون والصلاحيات", addTeamMember: "إضافة عضو فريق", newAdmin: "حساب مسؤول جديد", teamDescription: "دليل الأطباء والموظفين المهنيين.", usersDescription: "حسابات الدخول وحالة الأمان وانتقالات الصلاحيات المحمية.",
  search: "بحث", searchPlaceholder: "الاسم أو البريد الإلكتروني", role: "الدور", allRoles: "كل الأدوار", doctor: "طبيب", staff: "موظف", admin: "مسؤول", professionalStatus: "الحالة المهنية", allStatuses: "كل الحالات", active: "نشط", inactive: "غير نشط", availability: "التوفر", allAvailability: "كل حالات التوفر", available: "متاح", onLeave: "في إجازة", unavailable: "غير متاح", clearFilters: "مسح عوامل التصفية", loadingTeam: "جارٍ تحميل أعضاء الفريق", teamUnavailable: "أعضاء الفريق غير متاحين", retry: "إعادة المحاولة", refreshing: "جارٍ التحديث…", teamMembers: "أعضاء الفريق", noTeamMembers: "لا يوجد أعضاء فريق يطابقون عوامل التصفية", name: "الاسم", account: "الحساب", today: "اليوم", noSpecialty: "لا يوجد اختصاص", noPosition: "لا يوجد منصب", appointments: "مواعيد", activeVisits: "زيارات نشطة", previous: "السابق", next: "التالي", page: "الصفحة",
  addTitle: "إضافة عضو فريق", addDescription: "ينشئ حساب دخول وملفًا مهنيًا مطابقًا معًا.", accountSection: "الحساب", fullName: "الاسم الكامل", email: "البريد الإلكتروني", temporaryPassword: "كلمة المرور المؤقتة", professionalProfile: "الملف المهني", specialty: "الاختصاص", phone: "الهاتف", bio: "نبذة", position: "المنصب", createTeamMember: "إنشاء عضو الفريق", unableCreateTeam: "تعذر إنشاء عضو الفريق",
  openUsers: "فتح المستخدمين والصلاحيات", professionalProfileSummary: "الملف المهني", loginAccount: "حساب الدخول", passwordState: "حالة كلمة المرور", passwordCurrent: "كلمة المرور محدثة", mustChangePassword: "يجب تغيير كلمة المرور", workloadToday: "عبء العمل اليوم", deactivateProfessional: "تعطيل الملف المهني", reactivateProfessional: "إعادة تفعيل الملف المهني", professionalInformation: "المعلومات المهنية", profileChanged: "تم تغيير هذا الملف في مكان آخر. ما زالت تعديلاتك محفوظة هنا.", reloadLatest: "إعادة تحميل أحدث سجل", saveProfessional: "حفظ الملف المهني", workingHours: "ساعات العمل", noWorkingHours: "لم يتم إرجاع ساعات عمل نشطة.", leaveExceptions: "استثناءات الإجازة", noLeave: "لم يتم إرجاع إجازات حالية أو مستقبلية.", confirmProfessionalStatus: "تأكيد الحالة المهنية", professionalStatusDescription: "التوفر المهني منفصل عن صلاحية الدخول للحساب.", deactivateProfessionalQuestion: "هل تريد تعطيل هذا الملف المهني؟ لن يتغير حساب الدخول.", reactivateProfessionalQuestion: "هل تريد إعادة تفعيل هذا الملف المهني؟ لن يتغير حساب الدخول.", confirm: "تأكيد", cancel: "إلغاء", backToTeam: "العودة إلى الفريق",
  loadingAccounts: "جارٍ تحميل الحسابات", accountsUnavailable: "الحسابات غير متاحة", accounts: "الحسابات", password: "كلمة المرور", profile: "الملف", updated: "آخر تحديث", noAccounts: "لم يتم إرجاع حسابات", newAdminTitle: "حساب مسؤول جديد", newAdminDescription: "تتم إضافة الأطباء والموظفين من خلال الفريق.", createAdmin: "إنشاء حساب مسؤول", doctorStaffTeam: "لإضافة طبيب أو موظف، استخدم إضافة عضو فريق.", unableCreateAccount: "تعذر إنشاء الحساب", accountIdentity: "هوية الحساب", saveAccount: "حفظ الحساب", unableUpdateAccount: "تعذر تحديث الحساب", security: "الأمان", passwordCurrentDescription: "كلمة المرور محدثة.", passwordRequiredDescription: "يجب على المستخدم تغيير كلمة المرور عند تسجيل الدخول التالي.", resetPassword: "إعادة تعيين كلمة المرور المؤقتة", loginStatus: "حالة الدخول", loginStatusDescription: "صلاحية الدخول منفصلة عن حالة الملف المهني.", deactivateAccount: "تعطيل الحساب", reactivateAccount: "إعادة تفعيل الحساب", linkedTeam: "ملف الفريق المرتبط", openTeam: "فتح ملف الفريق", integrityWarning: "تحتاج سلامة الملف المهني إلى اهتمام", integrityDescription: "لا يمكن تمثيل هذا الحساب كعضو فريق حتى تصبح ارتباطات الخلفية متسقة.", created: "تاريخ الإنشاء", accountVersion: "إصدار الحساب", loadingAccount: "جارٍ تحميل الحساب", accountUnavailable: "الحساب غير متاح", backToUsers: "العودة إلى المستخدمين والصلاحيات",
  roleAccess: "الدور والصلاحيات", roleDescription: "تؤثر تغييرات الدور في صلاحيات مساحة العمل والارتباط المهني. وهي تتطلب معاينة وتأكيدًا من الخادم.", targetRole: "الدور المستهدف", previewRole: "معاينة انتقال الدور", operationalHistory: "السجل التشغيلي", confirmRole: "تأكيد انتقال الدور المحمي", transitionUnavailable: "تعذرت معاينة الانتقال", transitionConfirmUnavailable: "تعذر تأكيد الانتقال", resetDescription: "لا يتم الاحتفاظ بكلمة المرور بعد الإرسال.", resetUnavailable: "تعذر إعادة تعيين كلمة المرور", deactivateQuestion: "هل تريد تعطيل حساب الدخول هذا؟", reactivateQuestion: "هل تريد إعادة تفعيل حساب الدخول هذا؟", accountAccessDescription: "صلاحية الحساب منفصلة عن التوفر المهني.", accountAccessUnavailable: "تعذر تحديث صلاحية الدخول",
};

export const teamUsersCopy = (language: LanguagePreference): TeamUsersCopy => language === "AR" ? ar : en;
export function localizedEnum(language: LanguagePreference, value: string): string {
  const copy = teamUsersCopy(language);
  const labels: Record<string, string> = { ADMIN: copy.admin, DOCTOR: copy.doctor, STAFF: copy.staff, ACTIVE: copy.active, INACTIVE: copy.inactive, AVAILABLE: copy.available, ON_LEAVE: copy.onLeave, UNAVAILABLE: copy.unavailable, NONE: copy.account, PROFILE_SETUP_REQUIRED: copy.integrityWarning, INCONSISTENT: copy.integrityWarning };
  return labels[value] ?? value.split("_").join(" ");
}
