import type { LanguagePreference } from "../../types/auth";

const en = {
  team: "Team", usersAccess: "Users & Access", addTeamMember: "Add team member", newAdmin: "New Admin account", teamDescription: "Professional Doctor and Staff directory.", usersDescription: "Login accounts, security state, and protected access transitions.",
  search: "Search", searchPlaceholder: "Name or email", role: "Role", allRoles: "All roles", doctor: "Doctor", staff: "Staff", admin: "Admin", professionalStatus: "Professional status", allStatuses: "All statuses", active: "Active", inactive: "Inactive", availability: "Availability", allAvailability: "All availability", available: "Available", onLeave: "On leave", unavailable: "Unavailable", clearFilters: "Clear filters", loadingTeam: "Loading team members", teamUnavailable: "Team members are unavailable", retry: "Retry", refreshing: "Refreshing…", teamMembers: "Team members", noTeamMembers: "No team members match these filters", name: "Name", account: "Account", today: "Today", noSpecialty: "No specialty", noPosition: "No position", appointments: "appointments", activeVisits: "active visits", previous: "Previous", next: "Next", page: "Page",
  addTitle: "Add team member", addDescription: "Creates a login account and matching professional profile together.", accountSection: "Account", fullName: "Full name", email: "Email", temporaryPassword: "Temporary password", professionalProfile: "Professional profile", specialty: "Specialty", phone: "Phone", bio: "Bio", position: "Position", createTeamMember: "Create team member", unableCreateTeam: "Unable to create team member",
  openUsers: "Open Users & Access", professionalProfileSummary: "professional profile", loginAccount: "Login account", passwordState: "Password state", passwordCurrent: "Password current", mustChangePassword: "Must change password", workloadToday: "Workload today", deactivateProfessional: "Deactivate professional profile", reactivateProfessional: "Reactivate professional profile", professionalInformation: "Professional information", profileChanged: "This profile changed elsewhere. Your edits are still here.", reloadLatest: "Reload latest record", saveProfessional: "Save professional profile", workingHours: "Working hours", noWorkingHours: "No active working hours returned.", leaveExceptions: "Leave exceptions", noLeave: "No current or future leave returned.", confirmProfessionalStatus: "Confirm professional status", professionalStatusDescription: "Professional availability is separate from login account access.", deactivateProfessionalQuestion: "Deactivate this professional profile? The login account remains unchanged.", reactivateProfessionalQuestion: "Reactivate this professional profile? The login account remains unchanged.", confirm: "Confirm", cancel: "Cancel", backToTeam: "Back to Team",
  loadingAccounts: "Loading accounts", accountsUnavailable: "Accounts are unavailable", accounts: "Accounts", password: "Password", profile: "Profile", updated: "Updated", noAccounts: "No accounts returned", newAdminTitle: "New Admin account", newAdminDescription: "Doctor and Staff onboarding is managed from Team.", createAdmin: "Create Admin account", doctorStaffTeam: "To onboard a Doctor or Staff member, use Add team member.", unableCreateAccount: "Unable to create account", accountIdentity: "Account identity", saveAccount: "Save account", unableUpdateAccount: "Unable to update account", security: "Security", passwordCurrentDescription: "Password is current.", passwordRequiredDescription: "The user must change their password at next sign-in.", resetPassword: "Reset temporary password", loginStatus: "Login status", loginStatusDescription: "Login access is separate from any professional profile status.", deactivateAccount: "Deactivate account", reactivateAccount: "Reactivate account", linkedTeam: "Linked Team profile", openTeam: "Open Team profile", integrityWarning: "Professional profile integrity needs attention", integrityDescription: "This account cannot be represented as a Team member until backend linkage is consistent.", created: "Created", accountVersion: "Account version", loadingAccount: "Loading account", accountUnavailable: "Account unavailable", backToUsers: "Back to Users & Access",
  roleAccess: "Role and access", roleDescription: "Role changes affect workspace access and professional linkage. They require a server preview and confirmation.", targetRole: "Target role", previewRole: "Preview role transition", operationalHistory: "Operational history", confirmRole: "Confirm protected role transition", transitionUnavailable: "Unable to preview transition", transitionConfirmUnavailable: "Unable to confirm transition", resetDescription: "The password is not retained after submission.", resetUnavailable: "Unable to reset password", deactivateQuestion: "Deactivate this login account?", reactivateQuestion: "Reactivate this login account?", accountAccessDescription: "Account access is separate from professional availability.", accountAccessUnavailable: "Unable to update login access",
  filtersLoadedPage: "Filters apply to the loaded page.", readOnlyDirectory: "Read-only professional directory.", teamSummary: "Team summary", doctorsOnPage: "Doctors on page", availableOnPage: "Available on page", noReasonRecorded: "No reason recorded",
  accountSaved: "Account saved", effectiveAccess: "Effective Access", effectiveAccessDescription: "Role-derived access from the current saved role. Backend permissions remain authoritative.", manage: "Manage", readOnly: "Read only", ownRecords: "Own records", operational: "Operational", noAccess: "No access",
  patients: "Patients", clinicalVisits: "Clinical visits", xraysAi: "X-rays & AI", billingInvoices: "Billing / invoices", payments: "Payments", usersAccessCategory: "Users & Access", schedulesLeave: "Schedules / Leave", clinicSettings: "Clinic settings", auditLogs: "Audit logs",
  securityLogin: "Security & Login", current: "Current", accountIdentityDescription: "Update login identity separately from role access.", roleAccessChange: "Role & Access Change", currentRole: "Current role", newRole: "New role", saveRoleChange: "Save role change", reviewRoleChange: "Review role change", reviewRoleDescription: "Review the server safety preview before anything changes.", consequences: "Consequences", blockers: "Blockers", noBlockers: "No blockers returned.", requiredProfile: "Required profile fields", confirmRoleChange: "Confirm role change", profileForDoctor: "Doctor professional profile", profileForStaff: "Staff professional profile",
  linkedTeamProfile: "Linked Team Profile", linkedTeamLoading: "Loading linked professional profile", noProfessionalTeamProfile: "No professional Team profile", accountMetadata: "Account metadata", identitySaveSuccess: "Account identity saved.", passwordLabel: "Password", loginLabel: "Login", contact: "Contact", todayWorkload: "Today's workload", schedule: "Schedule", leaveAvailability: "Leave / availability", biography: "Biography", notProvided: "Not provided", editProfessionalProfile: "Edit professional profile", editProfessionalDescription: "Change professional fields only. Role and login identity stay in Users & Access.", saveChanges: "Save changes", professionalChangesSaved: "Professional profile saved.", unableUpdateProfile: "Unable to update professional profile",
  consequenceCreateProfile: "A matching professional profile will be created or reactivated.", consequenceSameRole: "The account already has the requested role.", consequenceHistory: "Operational history is retained and cannot be detached from this account.", consequenceAtomic: "The role and matching professional profile will be changed atomically.", consequenceLastAdmin: "The last active Admin cannot transition away from ADMIN.",
} as const;

type TeamUsersCopy = { [Key in keyof typeof en]: string };
const ar: TeamUsersCopy = {
  team: "الفريق", usersAccess: "المستخدمون والصلاحيات", addTeamMember: "إضافة عضو فريق", newAdmin: "حساب مسؤول جديد", teamDescription: "دليل الأطباء والموظفين المهنيين.", usersDescription: "حسابات الدخول وحالة الأمان وانتقالات الصلاحيات المحمية.",
  search: "بحث", searchPlaceholder: "الاسم أو البريد الإلكتروني", role: "الدور", allRoles: "كل الأدوار", doctor: "طبيب", staff: "موظف", admin: "مسؤول", professionalStatus: "الحالة المهنية", allStatuses: "كل الحالات", active: "نشط", inactive: "غير نشط", availability: "التوفر", allAvailability: "كل حالات التوفر", available: "متاح", onLeave: "في إجازة", unavailable: "غير متاح", clearFilters: "مسح عوامل التصفية", loadingTeam: "جارٍ تحميل أعضاء الفريق", teamUnavailable: "أعضاء الفريق غير متاحين", retry: "إعادة المحاولة", refreshing: "جارٍ التحديث…", teamMembers: "أعضاء الفريق", noTeamMembers: "لا يوجد أعضاء فريق يطابقون عوامل التصفية", name: "الاسم", account: "الحساب", today: "اليوم", noSpecialty: "لا يوجد اختصاص", noPosition: "لا يوجد منصب", appointments: "مواعيد", activeVisits: "زيارات نشطة", previous: "السابق", next: "التالي", page: "الصفحة",
  addTitle: "إضافة عضو فريق", addDescription: "ينشئ حساب دخول وملفًا مهنيًا مطابقًا معًا.", accountSection: "الحساب", fullName: "الاسم الكامل", email: "البريد الإلكتروني", temporaryPassword: "كلمة المرور المؤقتة", professionalProfile: "الملف المهني", specialty: "الاختصاص", phone: "الهاتف", bio: "نبذة", position: "المنصب", createTeamMember: "إنشاء عضو الفريق", unableCreateTeam: "تعذر إنشاء عضو الفريق",
  openUsers: "فتح المستخدمين والصلاحيات", professionalProfileSummary: "الملف المهني", loginAccount: "حساب الدخول", passwordState: "حالة كلمة المرور", passwordCurrent: "كلمة المرور محدثة", mustChangePassword: "يجب تغيير كلمة المرور", workloadToday: "عبء العمل اليوم", deactivateProfessional: "تعطيل الملف المهني", reactivateProfessional: "إعادة تفعيل الملف المهني", professionalInformation: "المعلومات المهنية", profileChanged: "تم تغيير هذا الملف في مكان آخر. ما زالت تعديلاتك محفوظة هنا.", reloadLatest: "إعادة تحميل أحدث سجل", saveProfessional: "حفظ الملف المهني", workingHours: "ساعات العمل", noWorkingHours: "لم يتم إرجاع ساعات عمل نشطة.", leaveExceptions: "استثناءات الإجازة", noLeave: "لم يتم إرجاع إجازات حالية أو مستقبلية.", confirmProfessionalStatus: "تأكيد الحالة المهنية", professionalStatusDescription: "التوفر المهني منفصل عن صلاحية الدخول للحساب.", deactivateProfessionalQuestion: "هل تريد تعطيل هذا الملف المهني؟ لن يتغير حساب الدخول.", reactivateProfessionalQuestion: "هل تريد إعادة تفعيل هذا الملف المهني؟ لن يتغير حساب الدخول.", confirm: "تأكيد", cancel: "إلغاء", backToTeam: "العودة إلى الفريق",
  loadingAccounts: "جارٍ تحميل الحسابات", accountsUnavailable: "الحسابات غير متاحة", accounts: "الحسابات", password: "كلمة المرور", profile: "الملف", updated: "آخر تحديث", noAccounts: "لم يتم إرجاع حسابات", newAdminTitle: "حساب مسؤول جديد", newAdminDescription: "تتم إضافة الأطباء والموظفين من خلال الفريق.", createAdmin: "إنشاء حساب مسؤول", doctorStaffTeam: "لإضافة طبيب أو موظف، استخدم إضافة عضو فريق.", unableCreateAccount: "تعذر إنشاء الحساب", accountIdentity: "هوية الحساب", saveAccount: "حفظ الحساب", unableUpdateAccount: "تعذر تحديث الحساب", security: "الأمان", passwordCurrentDescription: "كلمة المرور محدثة.", passwordRequiredDescription: "يجب على المستخدم تغيير كلمة المرور عند تسجيل الدخول التالي.", resetPassword: "إعادة تعيين كلمة المرور المؤقتة", loginStatus: "حالة الدخول", loginStatusDescription: "صلاحية الدخول منفصلة عن حالة الملف المهني.", deactivateAccount: "تعطيل الحساب", reactivateAccount: "إعادة تفعيل الحساب", linkedTeam: "ملف الفريق المرتبط", openTeam: "فتح ملف الفريق", integrityWarning: "تحتاج سلامة الملف المهني إلى اهتمام", integrityDescription: "لا يمكن تمثيل هذا الحساب كعضو فريق حتى تصبح ارتباطات الخلفية متسقة.", created: "تاريخ الإنشاء", accountVersion: "إصدار الحساب", loadingAccount: "جارٍ تحميل الحساب", accountUnavailable: "الحساب غير متاح", backToUsers: "العودة إلى المستخدمين والصلاحيات",
  roleAccess: "الدور والصلاحيات", roleDescription: "تؤثر تغييرات الدور في صلاحيات مساحة العمل والارتباط المهني. وهي تتطلب معاينة وتأكيدًا من الخادم.", targetRole: "الدور المستهدف", previewRole: "معاينة انتقال الدور", operationalHistory: "السجل التشغيلي", confirmRole: "تأكيد انتقال الدور المحمي", transitionUnavailable: "تعذرت معاينة الانتقال", transitionConfirmUnavailable: "تعذر تأكيد الانتقال", resetDescription: "لا يتم الاحتفاظ بكلمة المرور بعد الإرسال.", resetUnavailable: "تعذر إعادة تعيين كلمة المرور", deactivateQuestion: "هل تريد تعطيل حساب الدخول هذا؟", reactivateQuestion: "هل تريد إعادة تفعيل حساب الدخول هذا؟", accountAccessDescription: "صلاحية الحساب منفصلة عن التوفر المهني.", accountAccessUnavailable: "تعذر تحديث صلاحية الدخول",
  filtersLoadedPage: "تُطبّق عوامل التصفية على الصفحة المحمّلة.", readOnlyDirectory: "دليل مهني للقراءة فقط.", teamSummary: "ملخص الفريق", doctorsOnPage: "الأطباء في الصفحة", availableOnPage: "المتاحون في الصفحة", noReasonRecorded: "لا يوجد سبب مسجل",
  accountSaved: "تم حفظ الحساب", effectiveAccess: "الصلاحيات الفعلية", effectiveAccessDescription: "صلاحيات مشتقة من الدور المحفوظ حاليًا. تبقى صلاحيات الخادم هي المرجع.", manage: "إدارة", readOnly: "قراءة فقط", ownRecords: "السجلات الخاصة", operational: "تشغيلي", noAccess: "لا صلاحية",
  patients: "المرضى", clinicalVisits: "الزيارات السريرية", xraysAi: "الأشعة والذكاء الاصطناعي", billingInvoices: "الفوترة والفواتير", payments: "المدفوعات", usersAccessCategory: "المستخدمون والصلاحيات", schedulesLeave: "الجداول والإجازات", clinicSettings: "إعدادات العيادة", auditLogs: "سجلات التدقيق",
  securityLogin: "الأمان وتسجيل الدخول", current: "محدثة", accountIdentityDescription: "حدّث هوية تسجيل الدخول بشكل منفصل عن صلاحيات الدور.", roleAccessChange: "تغيير الدور والصلاحيات", currentRole: "الدور الحالي", newRole: "الدور الجديد", saveRoleChange: "حفظ تغيير الدور", reviewRoleChange: "مراجعة تغيير الدور", reviewRoleDescription: "راجع معاينة الأمان من الخادم قبل تنفيذ أي تغيير.", consequences: "النتائج", blockers: "العوائق", noBlockers: "لم يعرض الخادم أي عوائق.", requiredProfile: "حقول الملف المطلوبة", confirmRoleChange: "تأكيد تغيير الدور", profileForDoctor: "الملف المهني للطبيب", profileForStaff: "الملف المهني للموظف",
  linkedTeamProfile: "ملف الفريق المرتبط", linkedTeamLoading: "جارٍ تحميل الملف المهني المرتبط", noProfessionalTeamProfile: "لا يوجد ملف مهني في الفريق", accountMetadata: "بيانات الحساب", identitySaveSuccess: "تم حفظ هوية الحساب.", passwordLabel: "كلمة المرور", loginLabel: "الدخول", contact: "التواصل", todayWorkload: "عبء العمل اليوم", schedule: "الجدول", leaveAvailability: "الإجازة والتوفر", biography: "النبذة", notProvided: "غير متوفر", editProfessionalProfile: "تعديل الملف المهني", editProfessionalDescription: "غيّر الحقول المهنية فقط. يبقى الدور وهوية الدخول ضمن المستخدمين والصلاحيات.", saveChanges: "حفظ التغييرات", professionalChangesSaved: "تم حفظ الملف المهني.", unableUpdateProfile: "تعذر تحديث الملف المهني",
  consequenceCreateProfile: "سيتم إنشاء ملف مهني مطابق أو إعادة تفعيله.", consequenceSameRole: "للحساب الدور المطلوب بالفعل.", consequenceHistory: "يتم الاحتفاظ بالسجل التشغيلي ولا يمكن فصله عن هذا الحساب.", consequenceAtomic: "سيتم تغيير الدور والملف المهني المطابق ضمن عملية واحدة.", consequenceLastAdmin: "لا يمكن تغيير دور آخر مسؤول نشط من مسؤول.",
};

export const teamUsersCopy = (language: LanguagePreference): TeamUsersCopy => language === "AR" ? ar : en;
export function localizedEnum(language: LanguagePreference, value: string): string {
  const copy = teamUsersCopy(language);
  const labels: Record<string, string> = { ADMIN: copy.admin, DOCTOR: copy.doctor, STAFF: copy.staff, ACTIVE: copy.active, INACTIVE: copy.inactive, AVAILABLE: copy.available, ON_LEAVE: copy.onLeave, UNAVAILABLE: copy.unavailable, NONE: copy.account, PROFILE_SETUP_REQUIRED: copy.integrityWarning, INCONSISTENT: copy.integrityWarning, working_shifts: copy.workingHours, doctor_availability_exceptions: copy.leaveExceptions, staff_availability_exceptions: copy.leaveExceptions, appointments: copy.appointments, visits: copy.clinicalVisits, NO_ROLE_CHANGE: copy.consequenceSameRole, ROLE_TRANSITION_BLOCKED_BY_HISTORY: copy.consequenceHistory, LAST_ACTIVE_ADMIN: copy.consequenceLastAdmin };
  return labels[value] ?? value.split("_").join(" ");
}

export function localizedConsequence(language: LanguagePreference, value: string): string {
  const copy = teamUsersCopy(language);
  const labels: Record<string, string> = {
    "A matching professional profile will be created or reactivated.": copy.consequenceCreateProfile,
    "The account already has the requested role.": copy.consequenceSameRole,
    "Operational history is retained and cannot be detached from this account.": copy.consequenceHistory,
    "The role and matching professional profile will be changed atomically.": copy.consequenceAtomic,
    "The last active Admin cannot transition away from ADMIN.": copy.consequenceLastAdmin,
  };
  return labels[value] ?? value;
}
