# Generated by Django 6.0.7 on 2026-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(default='Pearl Dental Clinic', max_length=255)),
                ('address', models.CharField(default='Damascus, Syria', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='Asia/Damascus', max_length=100)),
                ('capacity_per_slot', models.PositiveIntegerField(default=3)),
                ('default_appointment_duration_minutes', models.PositiveIntegerField(default=30)),
                ('allowed_durations_minutes', models.JSONField(default=list)),
                ('default_currency', models.CharField(choices=[('SYP', 'Syrian Pound'), ('USD', 'US Dollar')], default='SYP', max_length=3)),
                ('supported_currencies', models.JSONField(default=list)),
                ('default_language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=2)),
                ('ai_mode', models.CharField(choices=[('DJANGO_INTERNAL', 'Django internal'), ('SEPARATE_SERVICE', 'Separate service'), ('MOCK_ADAPTER', 'Mock adapter')], default='MOCK_ADAPTER', max_length=30)),
                ('ai_service_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Clinic settings',
            },
        ),
    ]
