# Generated by Django 6.0.7 on 2026-07-09 03:07

import apps.xrays.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to=apps.xrays.models.xray_upload_path)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xrays', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_xrays', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xrays', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='xrays_xraya_patient_c4e448_idx'), models.Index(fields=['visit', 'created_at'], name='xrays_xraya_visit_i_ebf2b3_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='xrays_xraya_uploade_512d4c_idx')],
            },
        ),
    ]
