# Generated by Django 6.0.7 on 2026-07-09 03:23

import apps.xrays.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        ('xrays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayattachment',
            name='source',
            field=models.CharField(choices=[('ACTIVE_VISIT', 'Active visit'), ('PATIENT_PROFILE', 'Patient profile'), ('EXTERNAL_WORKSPACE', 'External workspace')], default='ACTIVE_VISIT', max_length=30),
        ),
        migrations.CreateModel(
            name='ExternalXrayCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to=apps.xrays.models.external_xray_upload_path)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('ATTACHED_TO_PATIENT', 'Attached to patient'), ('DISCARDED', 'Discarded')], default='TEMPORARY', max_length=30)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('attached_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attached_external_xray_cases', to='patients.patient')),
                ('attached_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attached_external_xray_cases', to='visits.visit')),
                ('attached_xray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_cases', to='xrays.xrayattachment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_xray_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['uploaded_by', 'status', 'created_at'], name='xrays_exter_uploade_3f9859_idx'), models.Index(fields=['status', 'created_at'], name='xrays_exter_status_15c6c4_idx'), models.Index(fields=['attached_patient', 'created_at'], name='xrays_exter_attache_a00b54_idx')],
            },
        ),
    ]
