import type { LanguagePreference } from "../../types/auth";

const copy = {
  EN: {
    adminWorkspace: "Admin workspace", staffWorkspace: "Staff workspace", billing: "Billing", billingDescription: "Invoices, collections, and clinical handoffs in one financial workspace.", overview: "Overview", handoffs: "Handoffs", invoices: "Invoices",
    overviewTitle: "Billing overview", overviewDescription: "A compact view of today’s billing activity and outstanding balances.", newInvoice: "New invoice", invoicesToday: "Invoices today", pendingHandoffs: "Pending handoffs", openInvoices: "Open invoices", collectedToday: "Collected today", clinicDate: "Clinic date", viewToday: "View today’s invoices", reviewPending: "Review pending handoffs", viewOpen: "View open invoices",
    recentInvoices: "Recent invoices", recentDescription: "The latest invoices across billing history.", todayInvoices: "Today’s invoices", todayDescription: "Invoices issued on the current clinic date.", viewAllInvoices: "View all invoices", viewAllToday: "View all today", outstandingByCurrency: "Outstanding by currency", outstandingDescription: "Cancelled invoices do not contribute to outstanding balances.", invoiced: "Invoiced", paidAmount: "Paid", outstanding: "Outstanding",
    historyTitle: "Invoice history", historyDescription: "Search and review the complete invoice record using clinic-local dates.", today: "Today", last7: "7 days", last30: "30 days", allTime: "All time", custom: "Custom", from: "From", to: "To", search: "Search", searchPlaceholder: "Invoice number or patient name", status: "Status", currency: "Currency", allStatuses: "All statuses", allCurrencies: "All currencies", clearFilters: "Clear filters", invoiceCount: "Invoices", open: "Open", paid: "Paid", noInvoices: "No invoices found.", loadingInvoices: "Loading invoices…", unavailableInvoices: "Unable to load invoices", records: "records", page: "Page", previous: "Previous", next: "Next", invoice: "Invoice", invoiceNumber: "Invoice #", patient: "Patient", date: "Date", created: "Created", total: "Total", balance: "Balance", financialSummary: "Financial summary", period: "Selected period", noAmount: "No amount",
    unpaid: "Unpaid", partiallyPaid: "Partially paid", cancelled: "Cancelled", converted: "Converted to invoice", dismissed: "Dismissed", pending: "Pending", noRecentInvoices: "No recent invoices.", noTodayInvoices: "No invoices created today.", loadingOverview: "Loading billing overview…", unavailableOverview: "Unable to load billing overview",
  },
  AR: {
    adminWorkspace: "مساحة عمل المدير", staffWorkspace: "مساحة عمل الموظف", billing: "الفوترة", billingDescription: "الفواتير والتحصيل والإحالات السريرية في مساحة مالية واحدة.", overview: "نظرة عامة", handoffs: "الإحالات", invoices: "الفواتير",
    overviewTitle: "نظرة عامة على الفوترة", overviewDescription: "عرض موجز لنشاط الفوترة اليوم والأرصدة المستحقة.", newInvoice: "فاتورة جديدة", invoicesToday: "فواتير اليوم", pendingHandoffs: "الإحالات المعلقة", openInvoices: "الفواتير المفتوحة", collectedToday: "المحصّل اليوم", clinicDate: "تاريخ العيادة", viewToday: "عرض فواتير اليوم", reviewPending: "مراجعة الإحالات المعلقة", viewOpen: "عرض الفواتير المفتوحة",
    recentInvoices: "أحدث الفواتير", recentDescription: "أحدث الفواتير في سجل الفوترة.", todayInvoices: "فواتير اليوم", todayDescription: "الفواتير الصادرة في تاريخ العيادة الحالي.", viewAllInvoices: "عرض كل الفواتير", viewAllToday: "عرض كل فواتير اليوم", outstandingByCurrency: "المستحق حسب العملة", outstandingDescription: "الفواتير الملغاة لا تدخل في الأرصدة المستحقة.", invoiced: "قيمة الفواتير", paidAmount: "المدفوع", outstanding: "المستحق",
    historyTitle: "سجل الفواتير", historyDescription: "ابحث وراجع سجل الفواتير الكامل باستخدام تاريخ العيادة المحلي.", today: "اليوم", last7: "7 أيام", last30: "30 يوماً", allTime: "كل الوقت", custom: "مخصص", from: "من", to: "إلى", search: "بحث", searchPlaceholder: "رقم الفاتورة أو اسم المريض", status: "الحالة", currency: "العملة", allStatuses: "كل الحالات", allCurrencies: "كل العملات", clearFilters: "مسح عوامل التصفية", invoiceCount: "الفواتير", open: "مفتوحة", paid: "مدفوعة", noInvoices: "لا توجد فواتير.", loadingInvoices: "جارٍ تحميل الفواتير…", unavailableInvoices: "تعذر تحميل الفواتير", records: "سجلات", page: "الصفحة", previous: "السابق", next: "التالي", invoice: "الفاتورة", invoiceNumber: "رقم الفاتورة", patient: "المريض", date: "التاريخ", created: "تاريخ الإنشاء", total: "الإجمالي", balance: "الرصيد", financialSummary: "الملخص المالي", period: "الفترة المحددة", noAmount: "لا يوجد مبلغ",
    unpaid: "غير مدفوعة", partiallyPaid: "مدفوعة جزئياً", cancelled: "ملغاة", converted: "محولة إلى فاتورة", dismissed: "مرفوضة", pending: "معلقة", noRecentInvoices: "لا توجد فواتير حديثة.", noTodayInvoices: "لم تصدر فواتير اليوم.", loadingOverview: "جارٍ تحميل نظرة الفوترة…", unavailableOverview: "تعذر تحميل نظرة الفوترة",
  },
} as const;

export type BillingCopy = { [Key in keyof typeof copy.EN]: string };
export function billingCopy(language: LanguagePreference): BillingCopy { return copy[language]; }

export function billingStatusLabel(language: LanguagePreference, status: string): string {
  const c = billingCopy(language);
  return ({ UNPAID: c.unpaid, PARTIALLY_PAID: c.partiallyPaid, PAID: c.paid, CANCELLED: c.cancelled, PENDING: c.pending, CONVERTED_TO_INVOICE: c.converted, DISMISSED: c.dismissed } as Record<string, string>)[status] ?? status.replace(/_/g, " ");
}
