import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { auditApi } from "../../api/endpoints/audit";
import { clinicApi } from "../../api/endpoints/clinic";
import { Card } from "../../components/Card";
import { EmptyState } from "../../components/EmptyState";
import { ErrorState } from "../../components/ErrorState";
import { LoadingState } from "../../components/LoadingState";
import { PageHeader } from "../../components/PageHeader";
import { StatusPill } from "../../components/StatusPill";

export function AdminClinicSettingsPage() { const settings = useQuery({ queryKey: ["clinic-settings"], queryFn: clinicApi.getSettings }); const client = useQueryClient(); const mutation = useMutation({ mutationFn: clinicApi.updateSettings, onSuccess: () => void client.invalidateQueries({ queryKey: ["clinic-settings"] }) }); const [values, setValues] = useState<Record<string, unknown> | null>(null); if (settings.isLoading) return <LoadingState title="Loading clinic settings..." />; if (settings.isError || !settings.data) return <ErrorState error={settings.error} title="Settings unavailable" />; const data = values ?? settings.data; return <div className="admin-page"><PageHeader eyebrow="admin workspace" title="Clinic Settings" description="Full Admin settings, including technical AI configuration." /><Card><form className="clinical-notes-form" onSubmit={(e) => { e.preventDefault(); mutation.mutate(data); }}>{Object.entries(data).map(([key, value]) => <label key={key}>{key.replace(/_/g, " ")}{Array.isArray(value) ? <input value={value.join(", ")} onChange={(e) => setValues({ ...data, [key]: e.target.value.split(",").map((part) => part.trim()).filter(Boolean) })} /> : <input value={String(value ?? "")} onChange={(e) => setValues({ ...data, [key]: typeof value === "number" ? Number(e.target.value) : e.target.value })} />}</label>)}{mutation.error ? <ErrorState error={mutation.error} title="Unable to update settings" /> : null}<div className="form-actions"><button className="button primary" disabled={mutation.isPending}>Save settings</button></div></form></Card></div>; }

function safeMetadata(value: unknown): string { if (!value || typeof value !== "object") return "No metadata"; return JSON.stringify(value, (key, current) => /password|token|secret|authorization|refresh|access/i.test(key) ? "[redacted]" : current, 2); }
export function AdminAuditLogListPage() { const [page, setPage] = useState(1); const audit = useQuery({ queryKey: ["audit-logs", page], queryFn: () => auditApi.list({ page }) }); return <div className="admin-page"><PageHeader eyebrow="admin workspace" title="Audit Logs" description="Read-only, backend-sanitized operational history." />{audit.isLoading ? <LoadingState title="Loading audit logs..." /> : null}{audit.isError ? <ErrorState error={audit.error} title="Audit logs unavailable" onRetry={() => void audit.refetch()} /> : null}{audit.data ? <><Card><div className="table-scroll"><table className="billing-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th /></tr></thead><tbody>{audit.data.results.map((log) => <tr key={log.id}><td>{log.created_at}</td><td>{log.actor?.full_name ?? "System"}</td><td>{log.action}</td><td>{log.entity_type} #{log.entity_id}</td><td><Link className="button secondary compact-button" to={`/admin/audit-logs/${log.id}`}>Open</Link></td></tr>)}</tbody></table></div></Card><div className="pagination-bar"><button className="button secondary" disabled={!audit.data.previous} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button className="button secondary" disabled={!audit.data.next} onClick={() => setPage(page + 1)}>Next</button></div></> : null}</div>; }
export function AdminAuditLogDetailPage() { const log = useQuery({ queryKey: ["audit-log", Number(useParams().auditLogId)], queryFn: () => auditApi.detail(Number(useParams().auditLogId)) }); if (log.isLoading) return <LoadingState title="Loading audit record..." />; if (log.isError || !log.data) return <ErrorState error={log.error} title="Audit record unavailable" />; return <div className="admin-page"><PageHeader eyebrow="admin workspace" title="Audit Record" description="Read-only sanitized metadata." /><Card><dl className="detail-grid"><div><dt>Time</dt><dd>{log.data.created_at}</dd></div><div><dt>Actor</dt><dd>{log.data.actor?.full_name ?? "System"}</dd></div><div><dt>Action</dt><dd>{log.data.action}</dd></div><div><dt>Entity</dt><dd>{log.data.entity_type} #{log.data.entity_id}</dd></div><div className="detail-wide"><dt>Metadata</dt><dd><pre className="print-data">{safeMetadata(log.data.metadata_json)}</pre></dd></div></dl></Card></div>; }
