import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Clock4, Grid2X2, List, Mail, Phone, UserPlus } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";

import { teamApi, teamQueryKeys } from "../../api/endpoints/team";
import { Button, ClickableRow, ConfirmDialog, DataTableShell, Field, FormSection, Modal, PageHeaderV2, Pagination, SectionHeading, SelectField, StatePanel, StatusBadge, SurfaceCard, Tabs, useOverlayClose } from "../../components/v2";
import { useFeatureT } from "../../layouts/i18n";
import type { AdminTeamMemberDetail, StaffTeamMemberDetail, TeamMemberCreatePayload, TeamMemberSummary, TeamMemberUpdatePayload } from "../../types/team";
import { getErrorMessage } from "../../utils/apiErrors";

type DirectoryRole = "ADMIN" | "STAFF";
type ViewMode = "cards" | "list";

function useTeamList(query: Record<string, string | number | undefined>) {
  return useQuery({ queryKey: [...teamQueryKeys.all, query], queryFn: () => teamApi.list(query), placeholderData: (previous) => previous });
}

function memberEmail(member: TeamMemberSummary) { return member.email; }
function roleLabel(member: TeamMemberSummary, t: ReturnType<typeof useFeatureT>) { return member.role === "DOCTOR" ? t("doctors") : t("staff"); }
function availabilityLabel(member: TeamMemberSummary, t: ReturnType<typeof useFeatureT>) { return member.availability.on_leave ? t("onLeave") : member.availability.availability === "AVAILABLE" ? t("available") : t("unavailable"); }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }

function DirectoryCard({ member, onOpen }: { member: TeamMemberSummary; onOpen: () => void }) {
  const t = useFeatureT();
  return <button type="button" className="team-directory-card" onClick={onOpen} aria-label={`${roleLabel(member, t)} ${member.full_name}`}>
    <span className="team-directory-card-header"><span className="team-directory-avatar" aria-hidden="true">{initials(member.full_name)}</span><span><strong className="bidi-isolate team-directory-truncate">{member.full_name}</strong><span className="team-directory-role">{roleLabel(member, t)}</span></span></span>
    <span className="team-directory-card-fields"><span><CalendarDays size={16} aria-hidden="true" /><span><small>{t("specialtyOrPosition")}</small><bdi>{member.specialty || member.position || t("notRecorded")}</bdi></span></span><span><Phone size={16} aria-hidden="true" /><span><small>{t("phone")}</small><bdi>{member.phone || t("noContactValue")}</bdi></span></span><span><Mail size={16} aria-hidden="true" /><span><small>{t("email")}</small><bdi className="bidi-isolate team-directory-truncate">{memberEmail(member) || t("noContactValue")}</bdi></span></span></span>
    <span className="team-directory-card-status"><StatusBadge status={member.professional_status} /><span className="team-directory-availability">{availabilityLabel(member, t)}</span></span>
    <span className="team-directory-card-metrics"><span><Clock4 size={16} aria-hidden="true" />{member.schedule_summary.has_active_schedule ? t("activeSchedule") : t("noActiveSchedule")} · <bdi>{member.schedule_summary.active_shift_count}</bdi></span><span><CalendarDays size={16} aria-hidden="true" />{t("todayAppointments")}: <bdi>{member.today_workload.appointment_count}</bdi></span><span>{t("activeVisit")}: <bdi>{member.today_workload.active_visit_count}</bdi></span></span>
  </button>;
}

interface TeamFormProps { member?: AdminTeamMemberDetail; onClose: () => void; onDirtyChange: (dirty: boolean) => void; onPendingChange: (pending: boolean) => void; }
function TeamForm({ member, onClose, onDirtyChange, onPendingChange }: TeamFormProps) {
  const client = useQueryClient(); const navigate = useNavigate(); const t = useFeatureT();
  const [role, setRole] = useState<"DOCTOR" | "STAFF">(member?.role ?? "DOCTOR"); const [fullName, setFullName] = useState(member?.full_name ?? ""); const [email, setEmail] = useState(member?.account.email ?? ""); const [password, setPassword] = useState(""); const [specialty, setSpecialty] = useState(member?.specialty ?? ""); const [position, setPosition] = useState(member?.position ?? ""); const [phone, setPhone] = useState(member?.phone ?? ""); const [bio, setBio] = useState(member?.role === "DOCTOR" && "bio" in member.profile ? member.profile.bio : "");
  const initial = useRef(""); const requestClose = useOverlayClose(); const values = { role, fullName, email, password, specialty, position, phone, bio };
  useEffect(() => { initial.current = JSON.stringify(values); onDirtyChange(false); }, []);
  useEffect(() => onDirtyChange(JSON.stringify(values) !== initial.current), [bio, email, fullName, onDirtyChange, password, phone, position, role, specialty]);
  const mutation = useMutation({ mutationFn: async () => {
    if (member) { const payload: TeamMemberUpdatePayload = role === "DOCTOR" ? { version: member.version, specialty, phone, bio } : { version: member.version, position, phone }; return teamApi.update(member.id, payload); }
    const payload: TeamMemberCreatePayload = role === "DOCTOR" ? { account: { full_name: fullName, email, temporary_password: password }, role, doctor_profile: { specialty, phone, bio } } : { account: { full_name: fullName, email, temporary_password: password }, role, staff_profile: { position, phone } }; return teamApi.create(payload);
  }, onSuccess: (result) => { onDirtyChange(false); void client.invalidateQueries({ queryKey: teamQueryKeys.all }); void client.invalidateQueries({ queryKey: ["users"] }); if (member) { void client.invalidateQueries({ queryKey: teamQueryKeys.detail(member.id) }); onClose(); } else navigate(`/admin/team/${result.id}`); } });
  useEffect(() => onPendingChange(mutation.isPending), [mutation.isPending, onPendingChange]);
  return <form onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}>
    {!member ? <StatePanel state="readonly" title={t("setupRequired")} description={t("scheduleRequiredHelp")} /> : null}
    {!member ? <FormSection title={t("accountAccess")}><Field label={t("fullName")} required value={fullName} onChange={(event) => setFullName(event.target.value)} /><Field label={t("email")} type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /><Field label={t("temporaryPassword")} type="password" required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /></FormSection> : null}
    {!member ? <FormSection title={t("professionalRole")}><SelectField label={t("role")} value={role} onChange={(event) => setRole(event.target.value as "DOCTOR" | "STAFF")}><option value="DOCTOR">{t("doctors")}</option><option value="STAFF">{t("staff")}</option></SelectField></FormSection> : null}
    <FormSection title={t("professionalProfile")}>{role === "DOCTOR" ? <><Field label={t("specialty")} value={specialty} onChange={(event) => setSpecialty(event.target.value)} /><Field label={t("phone")} value={phone} onChange={(event) => setPhone(event.target.value)} /><Field label={t("biography")} value={bio} onChange={(event) => setBio(event.target.value)} /></> : <><Field label={t("position")} value={position} onChange={(event) => setPosition(event.target.value)} /><Field label={t("phone")} value={phone} onChange={(event) => setPhone(event.target.value)} /></>}</FormSection>
    {mutation.error ? <StatePanel state="error" title={t("error")} description={getErrorMessage(mutation.error)} /> : null}<div className="v2-sticky-actions"><Button type="button" variant="secondary" onClick={requestClose} disabled={mutation.isPending}>{t("cancel")}</Button><Button type="submit" loading={mutation.isPending}>{member ? t("saveProfile") : t("createTeamMember")}</Button></div>
  </form>;
}

function TeamDirectoryPage({ role }: { role: DirectoryRole }) {
  const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const t = useFeatureT(); const isAdmin = role === "ADMIN";
  const [open, setOpen] = useState(false); const [formDirty, setFormDirty] = useState(false); const [formPending, setFormPending] = useState(false); const [searchInput, setSearchInput] = useState(params.get("q") ?? "");
  const selectedRole = params.get("role") ?? ""; const page = Number(params.get("page") ?? "1"); const q = params.get("q") ?? ""; const status = params.get("professional_status") ?? ""; const availability = params.get("availability") ?? ""; const view: ViewMode = params.get("view") === "list" ? "list" : "cards";
  const list = useTeamList({ page, q: q || undefined, role: selectedRole || undefined, professional_status: status || undefined, availability: availability || undefined });
  useEffect(() => { setSearchInput(q); }, [q]);
  useEffect(() => { const timer = window.setTimeout(() => { if (searchInput !== q) { const next = new URLSearchParams(params); searchInput ? next.set("q", searchInput) : next.delete("q"); next.set("page", "1"); setParams(next); } }, 300); return () => window.clearTimeout(timer); }, [searchInput, q, params, setParams]);
  const set = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== "page" && key !== "view") next.set("page", "1"); setParams(next); };
  const openMember = (id: number) => navigate(`/${role.toLowerCase()}/team/${id}?${params.toString()}`); const closeForm = () => { setFormDirty(false); setFormPending(false); setOpen(false); };
  const results = list.data?.results ?? []; const emptyState = q || selectedRole || status || availability ? t("noTeamMatches") : t("emptyTeamDirectory");
  return <div className="admin-page team-directory-page"><PageHeaderV2 title={t("team")} description={t("professionalDirectory")} action={isAdmin ? <Button onClick={() => setOpen(true)}><UserPlus size={18} />{t("addTeamMember")}</Button> : undefined} />
    <Tabs selected={selectedRole || "ALL"} onSelect={(value) => set("role", value === "ALL" ? "" : value)} tabs={[{ id: "ALL", label: t("all") }, { id: "DOCTOR", label: t("doctors") }, { id: "STAFF", label: t("staff") }]} />
    <SurfaceCard className="team-directory-shell"><div className="team-directory-toolbar"><h3>{t("teamMembers")} {list.data ? <bdi>({list.data.count})</bdi> : null}</h3><div className="v2-table-toolbar"><input aria-label={t("searchTeam")} placeholder={t("searchNameOrEmail")} value={searchInput} onChange={(event) => setSearchInput(event.target.value)} /><select aria-label={t("professionalStatus")} value={status} onChange={(event) => set("professional_status", event.target.value)}><option value="">{t("allStatuses")}</option><option value="ACTIVE">{t("active")}</option><option value="INACTIVE">{t("inactive")}</option></select><select aria-label={t("available")} value={availability} onChange={(event) => set("availability", event.target.value)}><option value="">{t("allAvailability")}</option><option value="AVAILABLE">{t("available")}</option><option value="ON_LEAVE">{t("onLeave")}</option><option value="UNAVAILABLE">{t("unavailable")}</option></select><div className="team-view-toggle" role="group" aria-label={t("directoryPresentation")}><Button compact variant={view === "cards" ? "primary" : "secondary"} onClick={() => set("view", "cards")} aria-pressed={view === "cards"}><Grid2X2 size={16} />{t("cards")}</Button><Button compact variant={view === "list" ? "primary" : "secondary"} onClick={() => set("view", "list")} aria-pressed={view === "list"}><List size={16} />{t("list")}</Button></div></div></div>
      {list.isLoading && !list.data ? <StatePanel state="loading" title={t("loadingTeam")} /> : list.isError && !list.data ? <StatePanel state="error" title={t("error")} description={getErrorMessage(list.error)} action={<Button variant="secondary" onClick={() => void list.refetch()}>{t("retry")}</Button>} /> : !results.length ? <StatePanel state="empty" title={emptyState} /> : view === "cards" ? <><div className="team-directory-grid" aria-busy={list.isFetching || undefined}>{results.map((member) => <DirectoryCard key={member.id} member={member} onOpen={() => openMember(member.id)} />)}</div>{list.isFetching ? <p className="team-directory-refreshing">{t("refreshingTeam")}</p> : null}</> : <DataTableShell title={t("teamMembers")}><table><thead><tr><th>{t("professional")}</th><th>{t("role")}</th><th>{t("specialtyOrPosition")}</th><th>{t("contactIdentifiers")}</th><th>{t("status")}</th><th>{t("available")}</th><th>{t("scheduleStatus")}</th><th>{t("todayWorkload")}</th></tr></thead><tbody>{results.map((member) => <ClickableRow key={member.id} showDisclosure={false} ariaLabel={`${roleLabel(member, t)} ${member.full_name}`} onOpen={() => openMember(member.id)}><td><strong className="bidi-isolate">{member.full_name}</strong></td><td>{roleLabel(member, t)}</td><td className="bidi-isolate">{member.specialty || member.position || t("notRecorded")}</td><td><bdi>{member.phone || t("noContactValue")}</bdi><br /><small className="bidi-isolate">{memberEmail(member) || t("noContactValue")}</small></td><td><StatusBadge status={member.professional_status} /></td><td>{availabilityLabel(member, t)}</td><td>{member.schedule_summary.has_active_schedule ? t("activeSchedule") : t("noActiveSchedule")} · <bdi>{member.schedule_summary.active_shift_count}</bdi></td><td><bdi>{member.today_workload.appointment_count} / {member.today_workload.active_visit_count}</bdi></td></ClickableRow>)}</tbody></table></DataTableShell>}</SurfaceCard>
    {list.data ? <Pagination page={page} hasPrevious={Boolean(list.data.previous)} hasNext={Boolean(list.data.next)} onPrevious={() => set("page", String(page - 1))} onNext={() => set("page", String(page + 1))} /> : null}
    {isAdmin ? <Modal open={open} title={t("addTeamMember")} description={t("addProfessional")} onClose={closeForm} dirty={formDirty} pending={formPending}><TeamForm onDirtyChange={setFormDirty} onPendingChange={setFormPending} onClose={closeForm} /></Modal> : null}</div>;
}

export function AdminTeamListPage() { return <TeamDirectoryPage role="ADMIN" />; }
export function StaffTeamListPage() { return <TeamDirectoryPage role="STAFF" />; }

function TeamOperationalDetails({ member, tab = "overview" }: { member: Pick<StaffTeamMemberDetail, "active_shifts" | "current_future_leave" | "today_appointments">; tab?: "overview" | "schedule" | "leave" }) { const t = useFeatureT(); if (tab === "schedule") return <SurfaceCard><SectionHeading title={t("workingHours")} />{member.active_shifts.length ? <ul>{member.active_shifts.map((shift, index) => <li key={`${shift.weekday}-${shift.start_time}-${index}`}><bdi>{shift.name}: {shift.start_time}–{shift.end_time}</bdi></li>)}</ul> : <StatePanel state="empty" title={t("noActiveShifts")} />}</SurfaceCard>; if (tab === "leave") return <SurfaceCard><SectionHeading title={t("leaveExceptions")} />{member.current_future_leave.length ? <ul>{member.current_future_leave.map((leave, index) => <li key={`${leave.start_datetime}-${index}`}><bdi>{leave.start_datetime} – {leave.end_datetime}</bdi>: <bdi>{leave.reason || t("noReason")}</bdi></li>)}</ul> : <StatePanel state="empty" title={t("noCurrentLeave")} />}</SurfaceCard>; return <SurfaceCard><SectionHeading title={t("todayAppointments")} />{member.today_appointments.length ? <ul>{member.today_appointments.map((appointment, index) => <li key={`${appointment.start_datetime}-${index}`}><bdi>{appointment.patient_name}</bdi> · <bdi>{appointment.start_datetime}</bdi> · <StatusBadge status={appointment.status} /></li>)}</ul> : <StatePanel state="empty" title={t("noAppointmentsToday")} />}</SurfaceCard>; }

export function AdminTeamDetailPage() {
  const t = useFeatureT(); const id = Number(useParams().memberId); const [params, setParams] = useSearchParams(); const detail = useQuery({ queryKey: teamQueryKeys.detail(id), queryFn: () => teamApi.detail(id), enabled: id > 0 }); const client = useQueryClient(); const [edit, setEdit] = useState(false); const [editDirty, setEditDirty] = useState(false); const [editPending, setEditPending] = useState(false); const [statusOpen, setStatusOpen] = useState(false); const statusMutation = useMutation({ mutationFn: () => teamApi.setProfessionalStatus(id, { is_active: !(detail.data?.professional_status === "ACTIVE"), version: detail.data?.version ?? 0 }), onSuccess: () => { void client.invalidateQueries({ queryKey: teamQueryKeys.detail(id) }); void client.invalidateQueries({ queryKey: teamQueryKeys.all }); setStatusOpen(false); } }); const closeEdit = () => { setEditDirty(false); setEditPending(false); setEdit(false); };
  if (detail.isLoading) return <StatePanel state="loading" title={t("loading")} />; if (detail.isError || !detail.data) return <StatePanel state="error" title={t("error")} description={detail.error ? getErrorMessage(detail.error) : undefined} />; const member = detail.data; const label = roleLabel(member, t); const back = `/admin/team${params.toString() ? `?${params}` : ""}`; const setupRequired = member.operational_status === "SETUP_REQUIRED";
  const tab: string = (params.get("tab") === "schedule" || params.get("tab") === "leave" || params.get("tab") === "access") ? params.get("tab") ?? "overview" : "overview";
  const setTab = (nextTab: string) => { const next = new URLSearchParams(params); next.set("tab", nextTab); setParams(next); };
  return <div className="admin-page"><Link className="inline-back-link" to={back}>{t("backToTeam")}</Link><PageHeaderV2 title={member.full_name} description={`${label} ${t("professionalRecord")}`} action={<>{setupRequired ? <Link className="v2-button secondary" to={`/admin/doctors?employee=${member.id}&setup=1`}>{t("configureSchedule")}</Link> : <Button variant="secondary" onClick={() => setStatusOpen(true)}>{member.professional_status === "ACTIVE" ? t("setProfessionalInactive") : t("setProfessionalActive")}</Button>}<Button onClick={() => setEdit(true)}>{t("editProfile")}</Button></>} /><Tabs selected={tab} onSelect={setTab} tabs={[{ id: "overview", label: t("teamOverview") }, { id: "schedule", label: t("teamSchedule") }, { id: "leave", label: t("teamLeave") }, { id: "access", label: t("teamAccess") }]} />{tab === "overview" ? <><SurfaceCard major><SectionHeading title={t("generalInfo")} /><dl className="detail-grid"><div><dt>{t("role")}</dt><dd>{label}</dd></div><div><dt>{t("professionalStatus")}</dt><dd><StatusBadge status={member.professional_status} /></dd></div><div><dt>{t("operationalStatus")}</dt><dd><StatusBadge status={member.operational_status} /></dd></div><div><dt>{member.role === "DOCTOR" ? t("specialty") : t("position")}</dt><dd className="bidi-isolate">{member.specialty || member.position || t("notRecorded")}</dd></div><div><dt>{t("phone")}</dt><dd className="bidi-isolate">{member.phone || t("notRecorded")}</dd></div></dl></SurfaceCard><TeamOperationalDetails member={member} /></> : null}{tab === "schedule" ? <TeamOperationalDetails member={member} tab="schedule" /> : null}{tab === "leave" ? <TeamOperationalDetails member={member} tab="leave" /> : null}{tab === "access" ? <SurfaceCard><SectionHeading title={t("linkedAccount")} /><p><bdi>{member.account.email}</bdi> · {member.account.is_active ? t("loginActive") : t("loginInactive")}</p><Link className="v2-button secondary" to={`/admin/users/${member.account.id}`}>{t("openUsersAccess")}</Link></SurfaceCard> : null}<Modal open={edit} title={`${t("editProfile")}: ${label}`} onClose={closeEdit} dirty={editDirty} pending={editPending}><TeamForm member={member} onDirtyChange={setEditDirty} onPendingChange={setEditPending} onClose={closeEdit} /></Modal><ConfirmDialog open={statusOpen} title={t("changeProfessionalStatus")} description={t("professionalStatusHelp")} onClose={() => setStatusOpen(false)} pending={statusMutation.isPending}><p>{t("confirmProfessionalStatus")}</p>{statusMutation.error ? <StatePanel state="error" title={t("error")} description={getErrorMessage(statusMutation.error)} /> : null}<Button variant="danger" loading={statusMutation.isPending} onClick={() => statusMutation.mutate()}>{t("confirm")}</Button></ConfirmDialog></div>;
}

export function StaffTeamDetailPage() {
  const t = useFeatureT(); const id = Number(useParams().memberId); const [params, setParams] = useSearchParams(); const detail = useQuery({ queryKey: teamQueryKeys.detail(id), queryFn: () => teamApi.staffDetail(id), enabled: id > 0 });
  if (detail.isLoading) return <StatePanel state="loading" title={t("loading")} />; if (detail.isError || !detail.data) return <StatePanel state="error" title={t("error")} description={detail.error ? getErrorMessage(detail.error) : undefined} />; const member = detail.data; const back = `/staff/team${params.toString() ? `?${params}` : ""}`;
  const tab: string = params.get("tab") === "schedule" || params.get("tab") === "leave" ? params.get("tab") ?? "overview" : "overview";
  const setTab = (nextTab: string) => { const next = new URLSearchParams(params); next.set("tab", nextTab); setParams(next); };
  return <div className="admin-page"><Link className="inline-back-link" to={back}>{t("backToTeam")}</Link><PageHeaderV2 title={member.full_name} description={`${roleLabel(member, t)} ${t("professionalRecord")}`} /><Tabs selected={tab} onSelect={setTab} tabs={[{ id: "overview", label: t("teamOverview") }, { id: "schedule", label: t("teamSchedule") }, { id: "leave", label: t("teamLeave") }]} />{tab === "overview" ? <><SurfaceCard major><SectionHeading title={t("generalInfo")} /><dl className="detail-grid"><div><dt>{t("role")}</dt><dd>{roleLabel(member, t)}</dd></div><div><dt>{t("professionalStatus")}</dt><dd><StatusBadge status={member.professional_status} /></dd></div><div><dt>{t("available")}</dt><dd>{availabilityLabel(member, t)}</dd></div><div><dt>{member.role === "DOCTOR" ? t("specialty") : t("position")}</dt><dd className="bidi-isolate">{member.specialty || member.position || t("notRecorded")}</dd></div><div><dt>{t("phone")}</dt><dd className="bidi-isolate">{member.phone || t("noContactValue")}</dd></div><div><dt>{t("email")}</dt><dd className="bidi-isolate">{member.email || t("noContactValue")}</dd></div></dl></SurfaceCard><TeamOperationalDetails member={member} /></> : null}{tab === "schedule" ? <TeamOperationalDetails member={member} tab="schedule" /> : null}{tab === "leave" ? <TeamOperationalDetails member={member} tab="leave" /> : null}</div>;
}
