import { useNavigate } from "react-router-dom";
import { ClickableRow, DataTableShell } from "../../../components/v2";
import type { UserRole } from "../../../types/auth";
import type { BillingHandoff, Invoice } from "../../../types/billing";
import { formatDateTime } from "../../../utils/dates";
import { formatMoney, handoffStatusLabel, invoiceStatusLabel } from "../utils/billing";

export function HandoffList({ role, handoffs }: { role: UserRole; handoffs: BillingHandoff[] }) { const navigate = useNavigate(); return <DataTableShell title={role === "DOCTOR" ? "My billing handoffs" : "Billing handoffs"} state={!handoffs.length ? <p>No billing handoffs found.</p> : undefined}><table className="billing-table"><thead><tr><th>Patient</th><th>Visit</th><th>Doctor</th><th>Suggested amount</th><th>Status</th><th>Created</th></tr></thead><tbody>{handoffs.map((handoff) => <ClickableRow key={handoff.id} onOpen={() => navigate(`/${role.toLowerCase()}/billing/handoffs/${handoff.id}`)}><td className="bidi-isolate">{handoff.patient.full_name}</td><td className="bidi-isolate">{formatDateTime(handoff.visit.started_at)} · {handoff.visit.status}</td><td>{handoff.doctor.full_name}</td><td className="bidi-isolate">{handoff.suggested_amount && handoff.currency ? formatMoney(handoff.suggested_amount, handoff.currency) : "Not set"}</td><td>{handoffStatusLabel(handoff.status)}</td><td className="bidi-isolate">{formatDateTime(handoff.created_at)}</td></ClickableRow>)}</tbody></table></DataTableShell>; }
export function InvoiceList({ role, invoices }: { role: UserRole; invoices: Invoice[] }) { const navigate = useNavigate(); return <DataTableShell title="Invoices" state={!invoices.length ? <p>No invoices found.</p> : undefined}><table className="billing-table"><thead><tr><th>Invoice</th><th>Patient</th><th>Status</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Issued</th></tr></thead><tbody>{invoices.map((invoice) => <ClickableRow key={invoice.id} onOpen={() => navigate(`/${role.toLowerCase()}/billing/invoices/${invoice.id}`)}><td className="bidi-isolate">{invoice.invoice_number}</td><td className="bidi-isolate">{invoice.patient.full_name}</td><td>{invoiceStatusLabel(invoice.status)}</td><td className="bidi-isolate">{formatMoney(invoice.total_amount, invoice.currency)}</td><td className="bidi-isolate">{formatMoney(invoice.paid_amount, invoice.currency)}</td><td className="bidi-isolate">{formatMoney(invoice.remaining_amount, invoice.currency)}</td><td className="bidi-isolate">{formatDateTime(invoice.created_at)}</td></ClickableRow>)}</tbody></table></DataTableShell>; }
