import { useState } from "react";

import { Button, ConfirmDialog, Modal } from "../../../components/v2";
import type { BillingHandoffCreatePayload, HandoffConversionPayload, PaymentPayload } from "../../../types/billing";
import { isPositiveMoney } from "../utils/billing";

const currencies = <><option value="USD">USD</option><option value="SYP">SYP</option></>;
function Error({ error, message }: { error?: unknown; message: string }) { return error ? <p className="form-error" role="alert">{message}</p> : null; }

export function CreateHandoffDialog({ error, pending, onCancel, onSubmit }: { error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: BillingHandoffCreatePayload) => void }) {
  const [note, setNote] = useState(""); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD"); const [validation, setValidation] = useState(""); const dirty = Boolean(note || amount);
  return <Modal open wide title="Create billing handoff" description="Create one pending handoff for this completed visit." pending={pending} dirty={dirty} onClose={onCancel}><form className="clinical-notes-form" onSubmit={(event) => { event.preventDefault(); if (amount && !isPositiveMoney(amount)) { setValidation("Suggested amount must be a positive amount with up to two decimals."); return; } setValidation(""); onSubmit({ ...(note.trim() ? { note: note.trim() } : {}), ...(amount ? { suggested_amount: amount, currency: currency as "USD" | "SYP" } : {}) }); }}><label>Note<textarea rows={3} disabled={pending} value={note} onChange={(e) => setNote(e.target.value)} /></label><label>Suggested amount<input inputMode="decimal" disabled={pending} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<select value={currency} disabled={pending || !amount} onChange={(e) => setCurrency(e.target.value)}>{currencies}</select></label>{validation ? <p className="field-error" role="alert">{validation}</p> : null}<Error error={error} message="Unable to create billing handoff. Review the completed visit and try again." /><div className="form-actions"><Button variant="secondary" type="button" disabled={pending} onClick={onCancel}>Cancel</Button><Button type="submit" loading={pending}>Create handoff</Button></div></form></Modal>;
}

export function ConvertHandoffDialog({ suggestedAmount, suggestedCurrency, error, pending, onCancel, onSubmit }: { suggestedAmount: string | null; suggestedCurrency: "USD" | "SYP" | null; error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: HandoffConversionPayload) => void }) {
  const [amount, setAmount] = useState(suggestedAmount ?? ""); const [currency, setCurrency] = useState<"USD" | "SYP">(suggestedCurrency ?? "USD"); const [notes, setNotes] = useState(""); const [validation, setValidation] = useState(""); const dirty = Boolean(amount || notes);
  return <Modal open title="Convert handoff to invoice" description="The backend creates the invoice and preserves the handoff history." pending={pending} dirty={dirty} onClose={onCancel}><form className="clinical-notes-form" onSubmit={(event) => { event.preventDefault(); if (!isPositiveMoney(amount)) { setValidation("A positive total amount is required."); return; } setValidation(""); onSubmit({ total_amount: amount, currency, ...(notes.trim() ? { notes: notes.trim() } : {}) }); }}><label>Total amount<input inputMode="decimal" disabled={pending} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<select disabled={pending} value={currency} onChange={(e) => setCurrency(e.target.value as "USD" | "SYP")}>{currencies}</select></label><label>Notes<textarea rows={3} disabled={pending} value={notes} onChange={(e) => setNotes(e.target.value)} /></label>{validation ? <p className="field-error" role="alert">{validation}</p> : null}<Error error={error} message="Unable to convert this handoff. It may already be converted." /><div className="form-actions"><Button variant="secondary" type="button" disabled={pending} onClick={onCancel}>Cancel</Button><Button type="submit" loading={pending}>Convert</Button></div></form></Modal>;
}

export function PaymentDialog({ currency, remaining, error, pending, onCancel, onSubmit }: { currency: "USD" | "SYP"; remaining: string; error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: PaymentPayload) => void }) {
  const [amount, setAmount] = useState(""); const [notes, setNotes] = useState(""); const [validation, setValidation] = useState(""); const dirty = Boolean(amount || notes);
  return <Modal open title="Record payment" description={`Remaining balance: ${remaining} ${currency}.`} pending={pending} dirty={dirty} onClose={onCancel}><form className="clinical-notes-form" onSubmit={(event) => { event.preventDefault(); if (!isPositiveMoney(amount)) { setValidation("Payment amount must be positive."); return; } if (Number(amount) > Number(remaining)) { setValidation("Payment cannot exceed the remaining balance."); return; } setValidation(""); onSubmit({ amount, currency, ...(notes.trim() ? { notes: notes.trim() } : {}) }); }}><label>Amount<input inputMode="decimal" disabled={pending} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<input value={currency} readOnly /></label><label>Notes<textarea rows={3} disabled={pending} value={notes} onChange={(e) => setNotes(e.target.value)} /></label>{validation ? <p className="field-error" role="alert">{validation}</p> : null}<Error error={error} message="Payment was not recorded. Review the balance and try again." /><div className="form-actions"><Button variant="secondary" type="button" disabled={pending} onClick={onCancel}>Cancel</Button><Button type="submit" loading={pending}>Record payment</Button></div></form></Modal>;
}

export function ReasonDialog({ title, description, submitLabel, pending, error, onCancel, onSubmit }: { title: string; description: string; submitLabel: string; pending: boolean; error?: unknown; onCancel: () => void; onSubmit: (reason?: string) => void }) { const [reason, setReason] = useState(""); return <ConfirmDialog open title={title} description={description} pending={pending} dirty={Boolean(reason)} onClose={onCancel}><label>Reason (optional)<textarea rows={3} disabled={pending} value={reason} onChange={(event) => setReason(event.target.value)} /></label><Error error={error} message="The billing action was not completed. Please retry." /><div className="form-actions"><Button variant="secondary" type="button" disabled={pending} onClick={onCancel}>Keep record</Button><Button variant="danger" type="button" loading={pending} onClick={() => onSubmit(reason.trim() || undefined)}>{submitLabel}</Button></div></ConfirmDialog>; }
