import { useState } from "react";
import { ErrorState } from "../../../components/ErrorState";
import type { BillingHandoffCreatePayload, HandoffConversionPayload, PaymentPayload } from "../../../types/billing";

function Dialog({ title, children }: { title: string; children: React.ReactNode }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog-panel" role="dialog" aria-modal="true" aria-label={title}><h3>{title}</h3>{children}</section></div>; }

export function CreateHandoffDialog({ error, pending, onCancel, onSubmit }: { error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: BillingHandoffCreatePayload) => void }) {
  const [note, setNote] = useState(""); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD"); const [validation, setValidation] = useState("");
  return <Dialog title="Create billing handoff"><form className="clinical-notes-form" onSubmit={(event) => { event.preventDefault(); if (amount && (!/^\d+(\.\d{1,2})?$/.test(amount) || Number(amount) <= 0)) return setValidation("Suggested amount must be positive."); setValidation(""); onSubmit({ note, suggested_amount: amount || null, currency: amount ? currency as "USD" | "SYP" : null }); }}><label>Note<textarea rows={3} value={note} onChange={(e) => setNote(e.target.value)} /></label><label>Suggested amount<input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<select value={currency} disabled={!amount} onChange={(e) => setCurrency(e.target.value)}><option value="USD">USD</option><option value="SYP">SYP</option></select></label>{validation ? <p className="field-error">{validation}</p> : null}{error ? <ErrorState error={error} title="Unable to create handoff" /> : null}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" disabled={pending}>Create handoff</button></div></form></Dialog>;
}

export function ConvertHandoffDialog({ error, pending, onCancel, onSubmit }: { error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: HandoffConversionPayload) => void }) {
  const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("USD"); const [notes, setNotes] = useState("");
  return <Dialog title="Convert handoff to invoice"><form className="clinical-notes-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ total_amount: amount || undefined, currency: amount ? currency as "USD" | "SYP" : undefined, notes }); }}><p className="form-note">Leave amount blank only when the backend can use the handoff suggestion.</p><label>Total amount<input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<select value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="USD">USD</option><option value="SYP">SYP</option></select></label><label>Notes<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} /></label>{error ? <ErrorState error={error} title="Unable to convert handoff" /> : null}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" disabled={pending}>Convert</button></div></form></Dialog>;
}

export function PaymentDialog({ currency, error, pending, onCancel, onSubmit }: { currency: "USD" | "SYP"; error?: unknown; pending: boolean; onCancel: () => void; onSubmit: (payload: PaymentPayload) => void }) {
  const [amount, setAmount] = useState(""); const [notes, setNotes] = useState("");
  return <Dialog title="Record payment"><form className="clinical-notes-form" onSubmit={(e) => { e.preventDefault(); onSubmit({ amount, currency, notes }); }}><label>Amount<input required inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Currency<input value={currency} readOnly /></label><label>Notes<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} /></label>{error ? <ErrorState error={error} title="Payment was not recorded" /> : null}<div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" disabled={pending}>Record payment</button></div></form></Dialog>;
}
