# Generated by Django 6.0.7 on 2026-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('CHECKED_IN', 'Checked in'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('NEEDS_RESCHEDULE', 'Needs reschedule')], default='UPCOMING', max_length=20),
        ),
    ]
