# Generated by Django 6.0.7 on 2026-07-10 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0003_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_previous_status',
            field=models.CharField(blank=True, choices=[('UPCOMING', 'Upcoming'), ('CHECKED_IN', 'Checked in'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('NEEDS_RESCHEDULE', 'Needs reschedule')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_source_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_appointments', to='scheduling.availabilityexception'),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_exceptions_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityexception',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reschedule_source_exception', 'status'], name='scheduling__resched_a09648_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['is_cancelled'], name='scheduling__is_canc_531cd4_idx'),
        ),
    ]
