from __future__ import annotations

from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q, Sum

from apps.common.models import TimeStampedModel


class BillingHandoff(TimeStampedModel):
    """Pearlix bill: one financial obligation, optionally generated by a Visit."""

    class Status(models.TextChoices):
        OPEN = "OPEN", "Open"
        PARTIALLY_PAID = "PARTIALLY_PAID", "Partially paid"
        PAID = "PAID", "Paid"
        CANCELLED = "CANCELLED", "Cancelled"

    class Currency(models.TextChoices):
        SYP = "SYP", "Syrian Pound"
        USD = "USD", "US Dollar"

    class Origin(models.TextChoices):
        VISIT_COMPLETION = "VISIT_COMPLETION", "Visit completion"
        MANUAL = "MANUAL", "Manual"
        LEGACY_MIGRATED = "LEGACY_MIGRATED", "Legacy migrated"

    patient = models.ForeignKey("patients.Patient", on_delete=models.PROTECT, related_name="billing_handoffs")
    visit = models.ForeignKey(
        "visits.Visit",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="billing_handoffs",
    )
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="billing_handoffs",
    )
    description = models.TextField()
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, choices=Currency.choices)
    note = models.TextField(blank=True)
    status = models.CharField(max_length=30, choices=Status.choices, default=Status.OPEN)
    origin = models.CharField(max_length=30, choices=Origin.choices, default=Origin.MANUAL)
    legacy_reference = models.TextField(blank=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)
    cancelled_reason = models.TextField(blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="billing_handoffs_created",
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="billing_handoffs_updated",
    )

    class Meta:
        indexes = [
            models.Index(fields=["status", "created_at"], name="billing_bil_status_245682_idx"),
            models.Index(fields=["doctor", "status"], name="billing_bil_doctor__34ec29_idx"),
            models.Index(fields=["patient", "created_at"], name="billing_bil_patient_2ebd12_idx"),
            models.Index(fields=["visit"], name="billing_bil_visit_i_dc1af3_idx"),
            models.Index(fields=["currency"], name="billing_bil_currency_idx"),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["visit"],
                condition=Q(visit__isnull=False),
                name="unique_billing_handoff_per_visit",
            ),
        ]
        ordering = ["-created_at", "-id"]

    def clean(self):
        errors = {}
        if self.doctor_id and self.doctor.role != "DOCTOR":
            errors["doctor"] = "Billing handoff doctor must have DOCTOR role."
        if self.visit_id:
            if self.patient_id and self.visit.patient_id != self.patient_id:
                errors["patient"] = "Billing handoff patient must match visit patient."
            if not self.doctor_id or self.visit.doctor_id != self.doctor_id:
                errors["doctor"] = "Billing handoff doctor must match visit doctor."
        if self.total_amount is not None and self.total_amount <= Decimal("0"):
            errors["total_amount"] = "Bill total must be positive."
        if not self.description or not self.description.strip():
            errors["description"] = "Bill description is required."
        if self.status == self.Status.CANCELLED and not self.cancelled_at:
            errors["cancelled_at"] = "Cancelled bills require cancelled_at."
        if errors:
            raise ValidationError(errors)

    @property
    def paid_amount(self) -> Decimal:
        annotated = getattr(self, "_paid_amount", None)
        if annotated is not None:
            return annotated
        total = self.invoices.aggregate(total=Sum("amount"))["total"]
        return total or Decimal("0.00")

    @property
    def remaining_amount(self) -> Decimal:
        remaining = self.total_amount - self.paid_amount
        return remaining if remaining > Decimal("0.00") else Decimal("0.00")

    @property
    def invoice_count(self) -> int:
        annotated = getattr(self, "_invoice_count", None)
        if annotated is not None:
            return annotated
        return self.invoices.count()

    def __str__(self) -> str:
        return f"Bill {self.id} for patient {self.patient_id}"


class Invoice(TimeStampedModel):
    """Pearlix invoice: one immutable payment receipt issued against a bill."""

    invoice_number = models.CharField(max_length=40, unique=True)
    billing_handoff = models.ForeignKey(
        BillingHandoff,
        on_delete=models.PROTECT,
        related_name="invoices",
    )
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    issued_at = models.DateTimeField()
    notes = models.TextField(blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="invoices_created",
    )

    class Meta:
        indexes = [
            models.Index(fields=["invoice_number"], name="billing_inv_invoice_70511c_idx"),
            models.Index(fields=["billing_handoff", "issued_at"], name="billing_inv_handoff_issued_idx"),
            models.Index(fields=["issued_at"], name="billing_inv_issued_idx"),
            models.Index(fields=["created_by", "created_at"], name="billing_inv_creator_idx"),
        ]
        ordering = ["-issued_at", "-id"]

    def clean(self):
        errors = {}
        if self.created_by_id and self.created_by.role != "STAFF":
            errors["created_by"] = "Invoice issuer must be a STAFF user."
        if self.amount is not None and self.amount <= Decimal("0"):
            errors["amount"] = "Invoice amount must be positive."
        if errors:
            raise ValidationError(errors)

    @property
    def patient(self):
        return self.billing_handoff.patient

    @property
    def patient_id(self):
        return self.billing_handoff.patient_id

    @property
    def currency(self) -> str:
        return self.billing_handoff.currency

    @property
    def description(self) -> str:
        return self.billing_handoff.description

    @property
    def visit(self):
        return self.billing_handoff.visit

    @property
    def visit_id(self):
        return self.billing_handoff.visit_id

    @property
    def appointment(self):
        return self.billing_handoff.visit.appointment if self.billing_handoff.visit_id else None

    @property
    def appointment_id(self):
        return self.billing_handoff.visit.appointment_id if self.billing_handoff.visit_id else None

    def __str__(self) -> str:
        return self.invoice_number


class InvoiceSequence(TimeStampedModel):
    scope = models.CharField(max_length=20, unique=True)
    last_number = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [models.Index(fields=["scope"])]
        ordering = ["scope"]

    def __str__(self) -> str:
        return f"{self.scope}: {self.last_number}"
